/*
  # Seed 150 Athlete Recipes - Batch 2 Global (fixed)
*/

INSERT INTO recipes (
  user_id, name, name_es, name_en, description, category,
  prep_time_min, cook_time_min, servings,
  ingredients, instructions,
  calories_kcal, carbs_g, protein_g, fat_g, fiber_g, sodium_mg,
  tags, suitable_for, image_url, is_public, culture
) VALUES

('00000000-0000-0000-0000-000000000000'::uuid,
 'Tortitas de Arroz Caseras para Carrera', 'Tortitas de Arroz Caseras para Carrera', 'Homemade Rice Cakes for Racing',
 'Inspiradas en la receta de Allen Lim. Alimento sólido durante triatlón y ciclismo. Alta concentración de carbohidratos en formato suave. / Inspired by Allen Lim recipe.',
 'during_race', 20, 30, 8,
 '[{"name":"Arroz de grano corto / Short grain rice","quantity":400,"unit":"g","calories":1380,"carbs":304,"protein":28,"fat":4},{"name":"Salsa de soja / Soy sauce","quantity":30,"unit":"ml","calories":18,"carbs":2,"protein":2,"fat":0},{"name":"Aceite de sésamo / Sesame oil","quantity":15,"unit":"ml","calories":135,"carbs":0,"protein":0,"fat":15}]',
 '1. Cocinar arroz con 150% agua (muy pegajoso). / Cook rice with 150% water (very sticky). 2. Mezclar arroz caliente con soja y aceite. / Mix hot rice with soy and oil. 3. Extender en bandeja, enfriar y cortar cuadrados. / Spread on tray, cool and cut squares. 4. Envolver en papel film individualmente. / Wrap in cling film individually.',
 1533, 306, 30, 19, 3, 900,
 '["tortitas de arroz","durante-carrera","ciclismo","triatlón","portátil"]',
 '["endurance","during-race","cycling","triathlon"]',
 'https://images.pexels.com/photos/6210747/pexels-photo-6210747.jpeg',
 true, 'global'),

('00000000-0000-0000-0000-000000000000'::uuid,
 'Dátiles con Mantequilla de Almendras', 'Dátiles con Mantequilla de Almendras', 'Dates with Almond Butter',
 'Energía de carbohidratos de absorción media con grasas saludables. Snack de carrera natural. Usado por ultramaratonistas. / Natural race snack used by ultramarathon runners.',
 'during_race', 5, 0, 1,
 '[{"name":"Dátiles Medjool / Medjool dates","quantity":60,"unit":"g","calories":167,"carbs":45,"protein":1,"fat":0},{"name":"Mantequilla de almendras / Almond butter","quantity":30,"unit":"g","calories":183,"carbs":6,"protein":7,"fat":16}]',
 '1. Abrir dátiles y retirar hueso. / Open dates and remove pit. 2. Rellenar con mantequilla de almendras. / Fill with almond butter. 3. Envolver en pares para llevar. / Wrap in pairs to carry.',
 350, 51, 8, 16, 4, 15,
 '["dátiles","almendras","snack carrera","energía natural","ultramaratón"]',
 '["endurance","during-race","ultra","natural"]',
 'https://images.pexels.com/photos/1346347/pexels-photo-1346347.jpeg',
 true, 'global'),

('00000000-0000-0000-0000-000000000000'::uuid,
 'Bolas de Energía de Avena y Cacao', 'Bolas de Energía de Avena y Cacao', 'Oat and Cacao Energy Balls',
 'Snack de energía hecho en casa. Sin cocción, listo en 15 minutos. Perfectas para entrenamientos y competencias. / Homemade energy snack. No baking, ready in 15 minutes.',
 'during_race', 15, 0, 12,
 '[{"name":"Avena / Oats","quantity":200,"unit":"g","calories":780,"carbs":130,"protein":28,"fat":14},{"name":"Mantequilla de maní / Peanut butter","quantity":120,"unit":"g","calories":720,"carbs":24,"protein":32,"fat":60},{"name":"Miel / Honey","quantity":60,"unit":"g","calories":180,"carbs":49,"protein":0,"fat":0},{"name":"Cacao en polvo / Cocoa powder","quantity":20,"unit":"g","calories":50,"carbs":10,"protein":4,"fat":2}]',
 '1. Mezclar todos los ingredientes en bowl. / Mix all ingredients in bowl. 2. Refrigerar 30 min. / Refrigerate 30 min. 3. Formar bolitas. / Shape into balls. 4. Refrigerar 1 hora antes de consumir. / Refrigerate 1 hour before eating.',
 1730, 213, 64, 76, 20, 480,
 '["bolas de energía","avena","cacao","sin horno","casero"]',
 '["endurance","during-race","training","snack"]',
 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
 true, 'global'),

('00000000-0000-0000-0000-000000000000'::uuid,
 'Bebida Isotónica Casera', 'Bebida Isotónica Casera', 'Homemade Isotonic Sports Drink',
 'Bebida deportiva casera sin azúcares artificiales. Reemplaza electrolitos perdidos durante el ejercicio. / Homemade sports drink without artificial sugars.',
 'during_race', 5, 0, 1,
 '[{"name":"Agua / Water","quantity":500,"unit":"ml","calories":0,"carbs":0,"protein":0,"fat":0},{"name":"Jugo de naranja / Orange juice","quantity":200,"unit":"ml","calories":88,"carbs":22,"protein":2,"fat":0},{"name":"Sal / Salt","quantity":1,"unit":"g","calories":0,"carbs":0,"protein":0,"fat":0},{"name":"Miel / Honey","quantity":20,"unit":"g","calories":60,"carbs":16,"protein":0,"fat":0}]',
 '1. Mezclar jugo de naranja con agua. / Mix orange juice with water. 2. Agregar sal y miel. / Add salt and honey. 3. Revolver bien. / Stir well.',
 148, 38, 2, 0, 0, 420,
 '["isotónica","casera","electrolitos","hidratación","económica"]',
 '["endurance","during-race","hydration"]',
 'https://images.pexels.com/photos/1346347/pexels-photo-1346347.jpeg',
 true, 'global'),

('00000000-0000-0000-0000-000000000000'::uuid,
 'Batido de Recuperación 4:1 Chocolate', 'Batido de Recuperación 4:1 Chocolate', '4:1 Recovery Shake Chocolate',
 'Relación ideal de carbohidratos:proteína para recuperación muscular. El ratio 4:1 maximiza síntesis proteica y relleno de glucógeno. / Ideal 4:1 carb:protein ratio for muscle recovery.',
 'post_race', 5, 0, 1,
 '[{"name":"Proteína de suero chocolate / Chocolate whey","quantity":30,"unit":"g","calories":120,"carbs":3,"protein":24,"fat":2},{"name":"Banana / Banana","quantity":150,"unit":"g","calories":134,"carbs":34,"protein":2,"fat":0},{"name":"Leche / Milk","quantity":300,"unit":"ml","calories":147,"carbs":14,"protein":10,"fat":8},{"name":"Miel / Honey","quantity":20,"unit":"g","calories":60,"carbs":16,"protein":0,"fat":0}]',
 '1. Licuar todos los ingredientes 30 segundos. / Blend all ingredients 30 seconds. 2. Consumir dentro de los 30 min post-ejercicio. / Consume within 30 min post-exercise.',
 461, 67, 36, 10, 3, 185,
 '["batido","recuperación","4:1","chocolate","proteína"]',
 '["endurance","post-race","recovery","high-protein"]',
 'https://images.pexels.com/photos/1346347/pexels-photo-1346347.jpeg',
 true, 'global'),

('00000000-0000-0000-0000-000000000000'::uuid,
 'Sopa de Pollo y Fideos Post-Carrera', 'Sopa de Pollo y Fideos Post-Carrera', 'Post-Race Chicken Noodle Soup',
 'La sopa de pollo repone sodio y glucógeno. Ideal para días de carrera larga con temperaturas extremas. / Chicken soup replenishes sodium and glycogen.',
 'post_race', 10, 30, 3,
 '[{"name":"Pechuga de pollo / Chicken breast","quantity":250,"unit":"g","calories":412,"carbs":0,"protein":77,"fat":9},{"name":"Fideos / Noodles","quantity":150,"unit":"g","calories":525,"carbs":108,"protein":18,"fat":2},{"name":"Zanahoria / Carrot","quantity":100,"unit":"g","calories":41,"carbs":10,"protein":1,"fat":0},{"name":"Caldo de pollo / Chicken broth","quantity":1000,"unit":"ml","calories":50,"carbs":3,"protein":5,"fat":2}]',
 '1. Hervir pollo en caldo 20 min. / Boil chicken in broth 20 min. 2. Retirar y desmenuzar. / Remove and shred. 3. Agregar fideos y zanahoria, cocinar 10 min. / Add noodles and carrot, cook 10 min. 4. Devolver pollo. / Return chicken.',
 1028, 121, 101, 13, 6, 1580,
 '["sopa","pollo","fideos","post-carrera","sodio"]',
 '["endurance","post-race","recovery","sodium"]',
 'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg',
 true, 'global'),

('00000000-0000-0000-0000-000000000000'::uuid,
 'Mate Cocido con Tostadas Integrales', 'Mate Cocido con Tostadas Integrales (Argentina)', 'Mate Tea with Whole Grain Toast (Argentina)',
 'Desayuno de los atletas del Río de la Plata. El mate aporta cafeína natural y antioxidantes. / Breakfast of Río de la Plata athletes. Mate provides natural caffeine.',
 'breakfast', 5, 5, 1,
 '[{"name":"Yerba mate / Yerba mate","quantity":50,"unit":"g","calories":20,"carbs":3,"protein":2,"fat":0},{"name":"Pan integral / Whole grain bread","quantity":80,"unit":"g","calories":208,"carbs":40,"protein":8,"fat":3},{"name":"Mantequilla de maní / Peanut butter","quantity":30,"unit":"g","calories":180,"carbs":6,"protein":8,"fat":15}]',
 '1. Preparar mate cocido. / Prepare mate tea. 2. Tostar el pan integral. / Toast the whole grain bread. 3. Untar con mantequilla de maní. / Spread with peanut butter.',
 408, 49, 18, 18, 6, 320,
 '["mate","Argentina","Uruguay","desayuno","cafeína natural"]',
 '["endurance","pre-training","caffeine"]',
 'https://images.pexels.com/photos/543730/pexels-photo-543730.jpeg',
 true, 'latin_american'),

('00000000-0000-0000-0000-000000000000'::uuid,
 'Empanadas de Pollo y Papa Argentinas', 'Empanadas de Pollo y Papa (Argentina)', 'Chicken and Potato Empanadas (Argentina)',
 'Empanadas horneadas ricas en carbohidratos y proteína. Portable y conveniente para entrenamientos. / Baked empanadas rich in carbs and protein. Portable and convenient.',
 'snack', 30, 25, 6,
 '[{"name":"Masa de empanada / Empanada dough","quantity":300,"unit":"g","calories":1050,"carbs":186,"protein":24,"fat":24},{"name":"Pollo desmenuzado / Shredded chicken","quantity":250,"unit":"g","calories":412,"carbs":0,"protein":77,"fat":9},{"name":"Papa cocida / Cooked potato","quantity":200,"unit":"g","calories":154,"carbs":35,"protein":4,"fat":0}]',
 '1. Mezclar pollo, papa y cebolla sofrita. / Mix chicken, potato and sautéed onion. 2. Cortar masa en círculos. / Cut dough into circles. 3. Colocar relleno y cerrar. / Place filling and seal. 4. Hornear a 200°C 20-25 min. / Bake at 200°C 20-25 min.',
 1616, 221, 105, 33, 12, 680,
 '["empanada","Argentina","horneada","pollo","portable"]',
 '["endurance","snack","meal-prep","portable"]',
 'https://images.pexels.com/photos/5949901/pexels-photo-5949901.jpeg',
 true, 'latin_american'),

('00000000-0000-0000-0000-000000000000'::uuid,
 'Cazuela de Pollo Chilena', 'Cazuela de Pollo con Papas (Chile)', 'Chilean Chicken Cazuela',
 'Sopa-guiso chilena con papa, zapallo y pollo. Alta densidad calórica para entrenamientos de resistencia. / Thick Chilean soup-stew with potato, squash and chicken.',
 'dinner', 15, 45, 3,
 '[{"name":"Pollo / Chicken","quantity":400,"unit":"g","calories":660,"carbs":0,"protein":80,"fat":36},{"name":"Papa / Potato","quantity":300,"unit":"g","calories":231,"carbs":52,"protein":6,"fat":0},{"name":"Zapallo / Squash","quantity":200,"unit":"g","calories":68,"carbs":17,"protein":2,"fat":0},{"name":"Choclo / Corn","quantity":150,"unit":"g","calories":173,"carbs":37,"protein":5,"fat":2}]',
 '1. Dorar pollo en olla grande. / Brown chicken in large pot. 2. Cubrir con caldo y hervir. / Cover with broth and boil. 3. Agregar papa, zapallo y choclo. / Add potato, squash and corn. 4. Cocinar 30-40 min. / Cook 30-40 min.',
 1132, 106, 93, 38, 10, 480,
 '["cazuela","Chile","pollo","papa","sopa","resistencia"]',
 '["endurance","high-calorie","recovery"]',
 'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg',
 true, 'latin_american'),

('00000000-0000-0000-0000-000000000000'::uuid,
 'Dal Tadka (Lentejas Indias)', 'Dal Tadka (Lentejas Indias Especiadas)', 'Dal Tadka (Indian Spiced Lentils)',
 'Lentejas amarillas con especias indias. Alta proteína vegetal y hierro. Popular entre corredores indios y vegetarianos. / Yellow lentils with Indian spices. High plant protein and iron.',
 'dinner', 10, 30, 3,
 '[{"name":"Lentejas amarillas / Yellow lentils","quantity":200,"unit":"g","calories":480,"carbs":82,"protein":34,"fat":2},{"name":"Ghee / Ghee","quantity":20,"unit":"g","calories":180,"carbs":0,"protein":0,"fat":20},{"name":"Especias (cúrcuma, comino) / Spices","quantity":10,"unit":"g","calories":30,"carbs":5,"protein":1,"fat":1},{"name":"Arroz basmati / Basmati rice","quantity":200,"unit":"g","calories":714,"carbs":158,"protein":14,"fat":2}]',
 '1. Hervir lentejas con cúrcuma 20 min. / Boil lentils with turmeric 20 min. 2. Sofreír cebolla en ghee, agregar especias. / Sauté onion in ghee, add spices. 3. Mezclar con lentejas y servir con arroz. / Mix with lentils and serve with rice.',
 1404, 245, 49, 25, 20, 420,
 '["dal","India","lentejas","especias","proteína vegetal","hierro"]',
 '["endurance","vegetarian","high-protein","iron-rich"]',
 'https://images.pexels.com/photos/5949901/pexels-photo-5949901.jpeg',
 true, 'asian'),

('00000000-0000-0000-0000-000000000000'::uuid,
 'Gachas de Mijo África Occidental', 'Gachas de Mijo (África Occidental)', 'Millet Porridge (West Africa)',
 'El mijo es el cereal más completo de África. Rico en hierro, magnesio y vitaminas B. Consumido por atletas de Mali, Senegal y Ghana. / Millet is the most nutritionally complete African cereal.',
 'breakfast', 5, 20, 2,
 '[{"name":"Mijo / Millet","quantity":160,"unit":"g","calories":590,"carbs":114,"protein":18,"fat":6},{"name":"Leche / Milk","quantity":300,"unit":"ml","calories":147,"carbs":14,"protein":10,"fat":8},{"name":"Azúcar morena / Brown sugar","quantity":30,"unit":"g","calories":116,"carbs":30,"protein":0,"fat":0},{"name":"Banana / Banana","quantity":100,"unit":"g","calories":89,"carbs":23,"protein":1,"fat":0}]',
 '1. Tostar mijo en sartén seco 3 min. / Toast millet in dry pan 3 min. 2. Agregar leche y cocinar 15-20 min revolviendo. / Add milk and cook 15-20 min stirring. 3. Endulzar y servir con banana. / Sweeten and serve with banana.',
 942, 181, 29, 14, 10, 160,
 '["mijo","África Occidental","desayuno","hierro","magnesio"]',
 '["endurance","vegetarian","iron-rich"]',
 'https://images.pexels.com/photos/543730/pexels-photo-543730.jpeg',
 true, 'west_african'),

('00000000-0000-0000-0000-000000000000'::uuid,
 'Falafel con Tabulé y Pan Pita', 'Falafel con Tabulé y Pan Pita', 'Falafel with Tabbouleh and Pita',
 'Proteína vegetal de garbanzo con ensalada de bulgur. Clásico mediterráneo de alta densidad nutricional. / Chickpea plant protein with bulgur salad.',
 'lunch', 20, 20, 2,
 '[{"name":"Garbanzos / Chickpeas","quantity":200,"unit":"g","calories":480,"carbs":82,"protein":26,"fat":8},{"name":"Bulgur / Bulgur","quantity":100,"unit":"g","calories":342,"carbs":76,"protein":12,"fat":2},{"name":"Pan pita / Pita bread","quantity":100,"unit":"g","calories":275,"carbs":56,"protein":9,"fat":2},{"name":"Aceite de oliva / Olive oil","quantity":20,"unit":"ml","calories":180,"carbs":0,"protein":0,"fat":20}]',
 '1. Procesar garbanzos con especias. / Process chickpeas with spices. 2. Formar bolitas y hornear 20 min. / Shape into balls and bake 20 min. 3. Preparar tabulé con bulgur y perejil. / Prepare tabbouleh with bulgur and parsley. 4. Servir falafel sobre pita. / Serve falafel over pita.',
 1277, 214, 47, 32, 22, 480,
 '["falafel","tabulé","Mediterráneo","garbanzo","proteína vegetal"]',
 '["endurance","vegetarian","high-protein"]',
 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
 true, 'middle_eastern'),

('00000000-0000-0000-0000-000000000000'::uuid,
 'Shakshuka Huevos en Salsa de Tomate', 'Shakshuka (Huevos en Salsa de Tomate)', 'Shakshuka (Eggs in Tomato Sauce)',
 'Plato de Oriente Medio y Norte de África. Huevos escalfados en salsa de tomate y especias. / Middle Eastern and North African dish. Eggs poached in tomato sauce.',
 'breakfast', 5, 20, 2,
 '[{"name":"Huevos / Eggs","quantity":200,"unit":"g","calories":308,"carbs":2,"protein":26,"fat":22},{"name":"Tomate triturado / Crushed tomato","quantity":400,"unit":"g","calories":80,"carbs":16,"protein":4,"fat":1},{"name":"Pimiento / Bell pepper","quantity":100,"unit":"g","calories":31,"carbs":7,"protein":1,"fat":0},{"name":"Aceite de oliva / Olive oil","quantity":20,"unit":"ml","calories":180,"carbs":0,"protein":0,"fat":20},{"name":"Pan integral / Whole grain bread","quantity":100,"unit":"g","calories":260,"carbs":50,"protein":10,"fat":3}]',
 '1. Sofreír cebolla y pimiento en aceite. / Sauté onion and pepper in oil. 2. Agregar tomate y especias, cocinar 10 min. / Add tomato and spices, cook 10 min. 3. Hacer hoyos y cascar los huevos. / Make holes and crack eggs. 4. Tapar y cocinar 8 min. Servir con pan. / Cover and cook 8 min. Serve with bread.',
 859, 75, 41, 46, 10, 540,
 '["shakshuka","Medio Oriente","huevo","tomate","desayuno"]',
 '["endurance","vegetarian","high-protein","breakfast"]',
 'https://images.pexels.com/photos/543730/pexels-photo-543730.jpeg',
 true, 'middle_eastern'),

('00000000-0000-0000-0000-000000000000'::uuid,
 'Bowl Proteína Greek Yogurt', 'Tazon de Proteína con Greek Yogurt', 'Greek Yogurt Protein Bowl',
 'Bowl de alto contenido proteico para deportistas de fuerza. La combinación entrega 40g+ de proteína. / High protein bowl for strength athletes delivering 40g+ protein.',
 'post_race', 5, 0, 1,
 '[{"name":"Yogur griego / Greek yogurt","quantity":200,"unit":"g","calories":130,"carbs":8,"protein":20,"fat":4},{"name":"Proteína en polvo / Protein powder","quantity":25,"unit":"g","calories":100,"carbs":2,"protein":20,"fat":1},{"name":"Granola / Granola","quantity":40,"unit":"g","calories":176,"carbs":29,"protein":4,"fat":5},{"name":"Fresas / Strawberries","quantity":100,"unit":"g","calories":32,"carbs":8,"protein":1,"fat":0},{"name":"Miel / Honey","quantity":15,"unit":"g","calories":46,"carbs":12,"protein":0,"fat":0}]',
 '1. Mezclar yogur griego con proteína en polvo. / Mix Greek yogurt with protein powder. 2. Colocar en bowl. / Place in bowl. 3. Agregar granola, fresas y miel. / Add granola, strawberries and honey.',
 484, 59, 45, 10, 4, 165,
 '["yogur griego","proteína","bowl","fuerza","post-entrenamiento"]',
 '["strength","high-protein","post-race","recovery"]',
 'https://images.pexels.com/photos/6210747/pexels-photo-6210747.jpeg',
 true, 'global'),

('00000000-0000-0000-0000-000000000000'::uuid,
 'Muslos Pollo Horneados Quinoa Tricolor', 'Muslos de Pollo al Horno con Quinoa Tricolor', 'Baked Chicken Thighs with Tricolor Quinoa',
 'Muslos de pollo jugosos con quinoa tricolor. Los muslos son más calóricos que la pechuga, ideal para atletas con alto gasto calórico. / Juicy chicken thighs with tricolor quinoa.',
 'dinner', 10, 40, 2,
 '[{"name":"Muslos de pollo / Chicken thighs","quantity":400,"unit":"g","calories":760,"carbs":0,"protein":68,"fat":54},{"name":"Quinoa tricolor / Tricolor quinoa","quantity":160,"unit":"g","calories":591,"carbs":103,"protein":23,"fat":10},{"name":"Aceite de oliva / Olive oil","quantity":20,"unit":"ml","calories":180,"carbs":0,"protein":0,"fat":20}]',
 '1. Marinar muslos con ajo y aceite. / Marinate thighs with garlic and oil. 2. Hornear a 190°C 35-40 min. / Bake at 190°C 35-40 min. 3. Cocinar quinoa tricolor. / Cook tricolor quinoa. 4. Servir pollo sobre quinoa. / Serve chicken over quinoa.',
 1531, 103, 91, 84, 12, 540,
 '["pollo","quinoa tricolor","proteína","horneado"]',
 '["endurance","high-protein","high-calorie"]',
 'https://images.pexels.com/photos/1640772/pexels-photo-1640772.jpeg',
 true, 'global'),

('00000000-0000-0000-0000-000000000000'::uuid,
 'Tostadas Francesas Proteicas', 'Tostadas Francesas con Proteína', 'High Protein French Toast',
 'Versión proteica del clásico desayuno con pan integral y huevos. Perfecto para desayuno pre-entrenamiento largo. / Protein version of the classic breakfast with whole grain bread and eggs.',
 'breakfast', 5, 10, 2,
 '[{"name":"Pan integral grueso / Thick whole grain bread","quantity":120,"unit":"g","calories":312,"carbs":60,"protein":12,"fat":4},{"name":"Huevos / Eggs","quantity":200,"unit":"g","calories":308,"carbs":2,"protein":26,"fat":22},{"name":"Leche / Milk","quantity":100,"unit":"ml","calories":49,"carbs":5,"protein":3,"fat":3},{"name":"Frutas del bosque / Mixed berries","quantity":100,"unit":"g","calories":50,"carbs":12,"protein":1,"fat":0}]',
 '1. Batir huevos con leche y canela. / Beat eggs with milk and cinnamon. 2. Remojar pan en mezcla de huevo. / Soak bread in egg mixture. 3. Dorar en sartén 3 min por lado. / Golden in pan 3 min per side. 4. Servir con berries. / Serve with berries.',
 719, 79, 42, 29, 8, 340,
 '["tostadas francesas","proteína","desayuno","integral","energía"]',
 '["endurance","high-protein","breakfast","pre-training"]',
 'https://images.pexels.com/photos/543730/pexels-photo-543730.jpeg',
 true, 'global'),

('00000000-0000-0000-0000-000000000000'::uuid,
 'Bowl Carne Molida Arroz Frijoles', 'Bowl de Carne Molida con Arroz y Frijoles', 'Ground Beef Rice and Bean Bowl',
 'Bowl completo de alta densidad calórica. Ideal para deportistas con entrenamiento de fuerza de alta intensidad. / Complete high-calorie bowl for strength athletes.',
 'dinner', 10, 20, 2,
 '[{"name":"Carne molida magra / Lean ground beef","quantity":250,"unit":"g","calories":522,"carbs":0,"protein":55,"fat":32},{"name":"Arroz / Rice","quantity":200,"unit":"g","calories":714,"carbs":158,"protein":14,"fat":2},{"name":"Frijoles negros / Black beans","quantity":150,"unit":"g","calories":240,"carbs":43,"protein":16,"fat":2}]',
 '1. Dorar carne molida en sartén con especias. / Brown ground beef in pan with spices. 2. Incorporar frijoles y cocinar 5 min. / Add beans and cook 5 min. 3. Servir sobre arroz cocido. / Serve over cooked rice.',
 1476, 201, 85, 36, 16, 620,
 '["carne molida","arroz","frijoles","bowl","proteína","fuerza"]',
 '["strength","high-protein","high-calorie"]',
 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
 true, 'global'),

('00000000-0000-0000-0000-000000000000'::uuid,
 'Pasta Arroz Integral Atún Pesto', 'Pasta de Arroz Integral con Atún y Pesto', 'Brown Rice Pasta with Tuna and Pesto',
 'Carga de carbohidratos para etapa de montaña. Sin gluten con pasta de arroz integral. Favorito de ciclistas profesionales. / Carbohydrate loading for mountain stage.',
 'pre_race', 15, 20, 2,
 '[{"name":"Pasta de arroz integral / Brown rice pasta","quantity":200,"unit":"g","calories":700,"carbs":150,"protein":12,"fat":4},{"name":"Atún / Tuna","quantity":150,"unit":"g","calories":180,"carbs":0,"protein":38,"fat":2},{"name":"Pesto / Pesto","quantity":50,"unit":"g","calories":250,"carbs":3,"protein":4,"fat":25},{"name":"Aceitunas / Olives","quantity":30,"unit":"g","calories":45,"carbs":2,"protein":0,"fat":5}]',
 '1. Cocinar pasta al dente. / Cook pasta al dente. 2. Mezclar caliente con pesto. / Mix hot with pesto. 3. Agregar atún y aceitunas. / Add tuna and olives.',
 1175, 155, 54, 36, 8, 640,
 '["pasta","arroz integral","ciclismo","sin gluten","carga carbohidratos"]',
 '["endurance","cycling","gluten-free","pre-race"]',
 'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg',
 true, 'european'),

('00000000-0000-0000-0000-000000000000'::uuid,
 'Banana con Mantequilla de Maní Bici', 'Banana con Mantequilla de Maní (Snack de Bici)', 'Banana with Peanut Butter (Cycling Snack)',
 'El snack de ciclismo más simple y efectivo. Carbohidratos rápidos de la banana con proteína del maní. / The simplest cycling snack. Fast carbs from banana with peanut protein.',
 'during_race', 2, 0, 1,
 '[{"name":"Banana / Banana","quantity":120,"unit":"g","calories":107,"carbs":27,"protein":1,"fat":0},{"name":"Mantequilla de maní / Peanut butter","quantity":30,"unit":"g","calories":180,"carbs":6,"protein":8,"fat":15}]',
 '1. Pelar banana. / Peel banana. 2. Untar con mantequilla de maní. / Spread with peanut butter. 3. Consumir durante la etapa. / Consume during the stage.',
 287, 33, 9, 15, 3, 115,
 '["banana","maní","ciclismo","snack","energía rápida"]',
 '["endurance","cycling","during-race","quick-energy"]',
 'https://images.pexels.com/photos/1346347/pexels-photo-1346347.jpeg',
 true, 'global'),

('00000000-0000-0000-0000-000000000000'::uuid,
 'Desayuno Nadador Alto Carbohidrato', 'Desayuno de Nadador (Alto Carbohidrato)', 'Swimmer High-Carb Breakfast',
 'Desayuno de alta densidad calórica para nadadores de distancia. Los nadadores tienen alto gasto calórico por el agua fría. / High calorie breakfast for distance swimmers.',
 'breakfast', 10, 10, 1,
 '[{"name":"Avena / Oats","quantity":100,"unit":"g","calories":390,"carbs":65,"protein":14,"fat":7},{"name":"Leche entera / Whole milk","quantity":350,"unit":"ml","calories":214,"carbs":16,"protein":12,"fat":12},{"name":"Banana / Banana","quantity":120,"unit":"g","calories":107,"carbs":27,"protein":1,"fat":0},{"name":"Mantequilla de maní / Peanut butter","quantity":40,"unit":"g","calories":240,"carbs":8,"protein":11,"fat":20}]',
 '1. Cocinar avena con leche 5-7 min. / Cook oats with milk 5-7 min. 2. Agregar banana aplastada. / Add mashed banana. 3. Servir con mantequilla de maní. / Serve with peanut butter.',
 951, 116, 38, 39, 10, 235,
 '["nadador","desayuno","alto carbohidrato","avena","energía"]',
 '["swimming","high-carb","high-calorie","breakfast"]',
 'https://images.pexels.com/photos/543730/pexels-photo-543730.jpeg',
 true, 'global'),

('00000000-0000-0000-0000-000000000000'::uuid,
 'Bowl Tofu Edamame Arroz Integral', 'Bowl de Tofu y Edamame con Arroz Integral', 'Tofu and Edamame Brown Rice Bowl',
 'Bowl vegano completo con proteína de soja de alta calidad. Excelente para atletas veganos. / Complete vegan bowl with high quality soy protein.',
 'lunch', 10, 30, 2,
 '[{"name":"Tofu firme / Firm tofu","quantity":300,"unit":"g","calories":240,"carbs":6,"protein":30,"fat":14},{"name":"Arroz integral / Brown rice","quantity":200,"unit":"g","calories":714,"carbs":150,"protein":16,"fat":6},{"name":"Edamame / Edamame","quantity":100,"unit":"g","calories":135,"carbs":10,"protein":14,"fat":6},{"name":"Salsa de soja / Soy sauce","quantity":20,"unit":"ml","calories":12,"carbs":1,"protein":2,"fat":0}]',
 '1. Marinar tofu en soja y sésamo. / Marinate tofu in soy and sesame. 2. Freír tofu hasta dorar. / Fry tofu until golden. 3. Cocinar arroz integral. / Cook brown rice. 4. Servir arroz con tofu y edamame. / Serve rice with tofu and edamame.',
 1101, 167, 62, 26, 14, 780,
 '["tofu","edamame","vegano","arroz integral","proteína completa"]',
 '["endurance","vegan","complete-protein","high-protein"]',
 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
 true, 'asian'),

('00000000-0000-0000-0000-000000000000'::uuid,
 'Chili Frijoles Múltiples Vegano', 'Chili de Frijoles Múltiples (Vegano)', 'Multi-Bean Chili (Vegan)',
 'Chili vegano con variedad de frijoles. Proteína vegetal completa y alto contenido de fibra. / Vegan chili with variety of beans. Complete plant protein and high fiber.',
 'dinner', 15, 40, 4,
 '[{"name":"Frijoles negros / Black beans","quantity":200,"unit":"g","calories":320,"carbs":58,"protein":21,"fat":2},{"name":"Frijoles rojos / Kidney beans","quantity":200,"unit":"g","calories":320,"carbs":58,"protein":22,"fat":1},{"name":"Garbanzos / Chickpeas","quantity":150,"unit":"g","calories":360,"carbs":60,"protein":20,"fat":6},{"name":"Tomate triturado / Crushed tomato","quantity":400,"unit":"g","calories":80,"carbs":16,"protein":4,"fat":1}]',
 '1. Sofreír cebolla, ajo y pimientos. / Sauté onion, garlic and peppers. 2. Agregar todos los frijoles y tomate. / Add all beans and tomato. 3. Incorporar especias y cocinar 30 min. / Add spices and cook 30 min.',
 1080, 192, 67, 10, 44, 580,
 '["chili","vegano","frijoles","fibra","proteína vegetal"]',
 '["endurance","vegan","high-fiber","high-protein"]',
 'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg',
 true, 'north_american'),

('00000000-0000-0000-0000-000000000000'::uuid,
 'Risotto Pollo y Champiñones', 'Risotto de Pollo y Champiñones', 'Chicken and Mushroom Risotto',
 'Arroz cremoso de liberación lenta de glucosa. Los champiñones aportan vitamina D y compuestos anti-inflamatorios. / Creamy rice with slow glucose release.',
 'dinner', 10, 35, 2,
 '[{"name":"Arroz arborio / Arborio rice","quantity":200,"unit":"g","calories":684,"carbs":150,"protein":12,"fat":2},{"name":"Pollo / Chicken","quantity":200,"unit":"g","calories":330,"carbs":0,"protein":40,"fat":18},{"name":"Champiñones / Mushrooms","quantity":200,"unit":"g","calories":44,"carbs":6,"protein":6,"fat":1},{"name":"Caldo de pollo / Chicken broth","quantity":600,"unit":"ml","calories":30,"carbs":2,"protein":3,"fat":1},{"name":"Parmesano / Parmesan","quantity":40,"unit":"g","calories":156,"carbs":0,"protein":14,"fat":11}]',
 '1. Sofreír pollo y retirar. / Sauté chicken and remove. 2. Agregar arroz y caldo poco a poco 25 min. / Add rice and broth little by little 25 min. 3. Agregar pollo, champiñones y parmesano. / Add chicken, mushrooms and parmesan.',
 1244, 158, 75, 32, 6, 740,
 '["risotto","pollo","champiñones","recuperación","anti-inflamatorio"]',
 '["endurance","recovery","anti-inflammatory"]',
 'https://images.pexels.com/photos/1640772/pexels-photo-1640772.jpeg',
 true, 'european'),

('00000000-0000-0000-0000-000000000000'::uuid,
 'Papas con Queso Snack Ultra', 'Papas con Queso y Tocino (Snack Ultra)', 'Cheese and Bacon Potatoes (Ultra Snack)',
 'Snack sólido de alta densidad calórica para ultramaratones. Las papas son la fuente más eficiente de carbohidratos durante actividad prolongada. / High-calorie solid snack for ultramarathons.',
 'during_race', 10, 15, 4,
 '[{"name":"Papa hervida pequeña / Small boiled potato","quantity":400,"unit":"g","calories":308,"carbs":70,"protein":8,"fat":0},{"name":"Queso fundido / Melted cheese","quantity":60,"unit":"g","calories":217,"carbs":2,"protein":14,"fat":17},{"name":"Tocino / Bacon","quantity":60,"unit":"g","calories":285,"carbs":0,"protein":15,"fat":25}]',
 '1. Hervir papas con sal. / Boil potatoes with salt. 2. Cocinar tocino hasta crocante. / Cook bacon until crispy. 3. Agregar queso fundido. / Add melted cheese. 4. Servir caliente en bolsa ziplock. / Serve hot in ziplock bag.',
 810, 72, 37, 42, 6, 1380,
 '["papa","queso","ultra","denso calórico","sólido","maratón"]',
 '["endurance","ultra","during-race","high-calorie"]',
 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
 true, 'global'),

('00000000-0000-0000-0000-000000000000'::uuid,
 'Sopa Miso con Tofu Japonesa', 'Sopa Miso con Tofu (Japón)', 'Miso Soup with Tofu (Japan)',
 'Sopa japonesa rica en probióticos del miso y proteína del tofu. Excelente para recuperación intestinal post-carrera. / Japanese soup rich in probiotics and protein.',
 'recovery', 5, 10, 2,
 '[{"name":"Pasta de miso / Miso paste","quantity":40,"unit":"g","calories":80,"carbs":10,"protein":5,"fat":2},{"name":"Tofu suave / Silken tofu","quantity":200,"unit":"g","calories":130,"carbs":4,"protein":14,"fat":7},{"name":"Alga wakame / Wakame seaweed","quantity":10,"unit":"g","calories":14,"carbs":2,"protein":1,"fat":0},{"name":"Dashi (caldo) / Dashi broth","quantity":600,"unit":"ml","calories":15,"carbs":1,"protein":2,"fat":0}]',
 '1. Calentar dashi sin hervir. / Heat dashi without boiling. 2. Disolver miso en caldo caliente. / Dissolve miso in hot broth. 3. Agregar tofu y wakame. / Add tofu and wakame.',
 239, 17, 22, 9, 3, 1680,
 '["miso","Japón","tofu","probióticos","recuperación intestinal"]',
 '["endurance","recovery","vegan","probiotics"]',
 'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg',
 true, 'asian'),

('00000000-0000-0000-0000-000000000000'::uuid,
 'Ceviche Camote Peruano', 'Bol de Ceviche de Camote (Perú)', 'Peruvian Ceviche Bowl with Sweet Potato',
 'Versión sport del ceviche peruano con camote. Rica en vitamina C, proteína de pescado y carbohidratos. / Sport version of Peruvian ceviche with sweet potato.',
 'post_race', 15, 20, 2,
 '[{"name":"Pescado blanco / White fish","quantity":300,"unit":"g","calories":330,"carbs":0,"protein":64,"fat":6},{"name":"Camote / Sweet potato","quantity":200,"unit":"g","calories":172,"carbs":40,"protein":3,"fat":0},{"name":"Limón / Lime","quantity":80,"unit":"g","calories":24,"carbs":8,"protein":0,"fat":0},{"name":"Ají amarillo / Yellow chili","quantity":20,"unit":"g","calories":10,"carbs":2,"protein":0,"fat":0}]',
 '1. Cortar pescado en cubos y marinar en limón 20 min. / Cut fish in cubes and marinate in lime 20 min. 2. Hervir camote y hacer rodajas. / Boil sweet potato and slice. 3. Mezclar pescado con cebolla y ají. / Mix fish with onion and chili. 4. Servir con camote. / Serve with sweet potato.',
 536, 50, 67, 6, 8, 380,
 '["ceviche","Perú","camote","vitamina C","proteína pescado"]',
 '["endurance","high-protein","vitamin-c","post-race"]',
 'https://images.pexels.com/photos/1640772/pexels-photo-1640772.jpeg',
 true, 'latin_american'),

('00000000-0000-0000-0000-000000000000'::uuid,
 'Lentejas Rojas Espinaca Turquía', 'Lentejas Rojas con Espinaca (Turquía)', 'Red Lentil Soup with Spinach (Turkey)',
 'Sopa cremosa de lentejas rojas con espinaca. Alta en hierro, folato y proteína vegetal. / Creamy red lentil soup with spinach. High in iron, folate and plant protein.',
 'dinner', 10, 25, 3,
 '[{"name":"Lentejas rojas / Red lentils","quantity":200,"unit":"g","calories":480,"carbs":82,"protein":34,"fat":2},{"name":"Espinaca / Spinach","quantity":150,"unit":"g","calories":35,"carbs":5,"protein":4,"fat":1},{"name":"Caldo / Broth","quantity":800,"unit":"ml","calories":40,"carbs":4,"protein":4,"fat":2},{"name":"Limón / Lemon","quantity":30,"unit":"g","calories":9,"carbs":3,"protein":0,"fat":0}]',
 '1. Hervir lentejas en caldo con cúrcuma 20 min. / Boil lentils in broth with turmeric 20 min. 2. Agregar espinaca y licuar parcialmente. / Add spinach and partially blend. 3. Servir con limón. / Serve with lemon.',
 564, 94, 42, 5, 18, 580,
 '["lentejas rojas","Turquía","espinaca","hierro","folato"]',
 '["endurance","vegetarian","iron-rich","high-protein"]',
 'https://images.pexels.com/photos/5949901/pexels-photo-5949901.jpeg',
 true, 'middle_eastern'),

('00000000-0000-0000-0000-000000000000'::uuid,
 'Arroz con Leche Deportivo', 'Arroz con Leche Deportivo', 'Athlete Rice Pudding',
 'Postre/snack post-entrenamiento con carbohidratos de absorción media y calcio. Popular en España y América Latina. / Post-training snack with medium-absorption carbs and calcium.',
 'recovery', 5, 25, 2,
 '[{"name":"Arroz / Rice","quantity":120,"unit":"g","calories":428,"carbs":94,"protein":8,"fat":1},{"name":"Leche entera / Whole milk","quantity":600,"unit":"ml","calories":366,"carbs":28,"protein":21,"fat":21},{"name":"Azúcar / Sugar","quantity":50,"unit":"g","calories":193,"carbs":50,"protein":0,"fat":0},{"name":"Canela / Cinnamon","quantity":3,"unit":"g","calories":8,"carbs":2,"protein":0,"fat":0}]',
 '1. Hervir leche con canela. / Boil milk with cinnamon. 2. Agregar arroz y cocinar 20-25 min revolviendo. / Add rice and cook 20-25 min stirring. 3. Endulzar y servir tibio. / Sweeten and serve warm.',
 995, 174, 29, 22, 3, 270,
 '["arroz con leche","recovery","postre","calcio","carbohidratos"]',
 '["endurance","recovery","calcium"]',
 'https://images.pexels.com/photos/6210747/pexels-photo-6210747.jpeg',
 true, 'latin_american'),

('00000000-0000-0000-0000-000000000000'::uuid,
 'Salmón Soba Edamame Teriyaki', 'Salmón Teriyaki con Edamame y Soba', 'Teriyaki Salmon with Edamame and Soba',
 'Fideos soba con salmón teriyaki y edamame. Alto en Omega-3 y proteína completa. / Soba noodles with teriyaki salmon and edamame. High in Omega-3 and complete protein.',
 'dinner', 15, 20, 2,
 '[{"name":"Fideos soba / Soba noodles","quantity":200,"unit":"g","calories":680,"carbs":140,"protein":28,"fat":4},{"name":"Salmón / Salmon","quantity":300,"unit":"g","calories":600,"carbs":0,"protein":66,"fat":36},{"name":"Edamame / Edamame","quantity":100,"unit":"g","calories":135,"carbs":10,"protein":14,"fat":6},{"name":"Salsa teriyaki / Teriyaki sauce","quantity":40,"unit":"ml","calories":56,"carbs":12,"protein":2,"fat":0}]',
 '1. Marinar salmón en teriyaki 15 min. / Marinate salmon in teriyaki 15 min. 2. Cocinar fideos soba. / Cook soba noodles. 3. Asar salmón en grill. / Grill salmon. 4. Servir soba con salmón y edamame. / Serve soba with salmon and edamame.',
 1471, 162, 110, 46, 10, 980,
 '["soba","salmón","teriyaki","omega-3","Japón"]',
 '["endurance","high-protein","omega3","low-GI"]',
 'https://images.pexels.com/photos/1640772/pexels-photo-1640772.jpeg',
 true, 'asian'),

('00000000-0000-0000-0000-000000000000'::uuid,
 'Muesli Bircher Suizo', 'Muesli Bircher (Suiza)', 'Bircher Muesli (Switzerland)',
 'El muesli original creado por Maximilian Bircher-Benner. Remojado en jugo de manzana. Digestión lenta ideal para larga distancia. / The original muesli soaked in apple juice.',
 'breakfast', 10, 0, 2,
 '[{"name":"Avena gruesa / Rolled oats","quantity":100,"unit":"g","calories":390,"carbs":65,"protein":14,"fat":7},{"name":"Jugo de manzana / Apple juice","quantity":200,"unit":"ml","calories":90,"carbs":22,"protein":0,"fat":0},{"name":"Manzana rallada / Grated apple","quantity":150,"unit":"g","calories":78,"carbs":21,"protein":0,"fat":0},{"name":"Nueces / Walnuts","quantity":30,"unit":"g","calories":196,"carbs":4,"protein":5,"fat":20},{"name":"Yogur / Yogurt","quantity":150,"unit":"g","calories":95,"carbs":11,"protein":8,"fat":4}]',
 '1. Remojar avena en jugo de manzana toda la noche. / Soak oats in apple juice overnight. 2. Mezclar con manzana rallada, yogur y miel. / Mix with grated apple, yogurt and honey. 3. Agregar nueces al servir. / Add nuts when serving.',
 849, 123, 27, 31, 10, 95,
 '["muesli bircher","Suiza","avena","manzana","digestión lenta"]',
 '["endurance","vegetarian","slow-release","breakfast"]',
 'https://images.pexels.com/photos/543730/pexels-photo-543730.jpeg',
 true, 'european'),

('00000000-0000-0000-0000-000000000000'::uuid,
 'Pancakes Avena Plátano Sin Harina', 'Pancakes de Avena y Plátano (Sin Harina)', 'Flourless Oat and Banana Pancakes',
 'Pancakes súper simples sin harina blanca. Solo 3 ingredientes. Perfectos para pre-entrenamiento o desayuno ligero. / Super simple flourless pancakes with only 3 ingredients.',
 'breakfast', 5, 10, 1,
 '[{"name":"Banana madura / Ripe banana","quantity":120,"unit":"g","calories":107,"carbs":27,"protein":1,"fat":0},{"name":"Avena / Oats","quantity":60,"unit":"g","calories":234,"carbs":39,"protein":8,"fat":4},{"name":"Huevo / Egg","quantity":60,"unit":"g","calories":93,"carbs":0,"protein":8,"fat":6}]',
 '1. Aplastar bien la banana con tenedor. / Mash banana well with fork. 2. Mezclar con avena y huevo. / Mix with oats and egg. 3. Cocinar en sartén antiadherente 2-3 min por lado. / Cook in non-stick pan 2-3 min per side.',
 434, 66, 17, 10, 6, 70,
 '["pancakes","sin harina","banana","avena","3 ingredientes"]',
 '["endurance","vegetarian","gluten-free","quick"]',
 'https://images.pexels.com/photos/543730/pexels-photo-543730.jpeg',
 true, 'global')

ON CONFLICT DO NOTHING;
