/*
  # Seed Athlete Recipes - Batch 3: Asia, Scandinavia, Caribbean, Southeast Asia

  Adds ~47 culturally diverse system recipes for athletes.
  Covers: Japanese, Korean, Chinese, Thai, Vietnamese, Indonesian,
  Sri Lankan, Bangladeshi, Scandinavian, Caribbean, Central American,
  Russian/Eastern European, South African.

  All recipes:
  - user_id = NULL (system recipes)
  - is_public = true
  - Bilingual: name_es, name_en, description
  - Include image_url from Pexels
  - Full nutritional data
*/

INSERT INTO recipes (
  user_id, name, name_es, name_en, culture, description, category,
  prep_time_min, cook_time_min, servings,
  ingredients, instructions,
  calories_kcal, carbs_g, protein_g, fat_g, fiber_g, sodium_mg,
  tags, suitable_for, image_url, is_public
) VALUES

-- JAPANESE
(NULL, 'Ramen de pollo y huevo / Chicken Egg Ramen', 'Ramen de pollo y huevo', 'Chicken Egg Ramen', 'japanese',
 'Reconfortante tazón de ramen con caldo de pollo, fideos y huevo | Comforting ramen bowl with chicken broth, noodles and egg',
 'recovery', 20, 25, 1,
 '[{"name":"fideos ramen / ramen noodles","quantity":100,"unit":"g","calories":356,"protein":12,"carbs":72,"fat":2},{"name":"pechuga de pollo / chicken breast","quantity":100,"unit":"g","calories":165,"protein":31,"carbs":0,"fat":4},{"name":"huevo / egg","quantity":2,"unit":"unidad","calories":155,"protein":13,"carbs":1,"fat":11},{"name":"caldo de pollo / chicken broth","quantity":500,"unit":"ml","calories":20,"protein":2,"carbs":2,"fat":0},{"name":"salsa de soja / soy sauce","quantity":15,"unit":"ml","calories":9,"protein":1,"carbs":1,"fat":0},{"name":"cebolla de verdeo / green onion","quantity":20,"unit":"g","calories":6,"protein":0,"carbs":1,"fat":0}]',
 '1. Cocinar fideos según indicaciones. 2. Preparar caldo caliente con caldo y soja. 3. Hervir huevos 7 min. 4. Agregar pollo cocido al caldo. 5. Servir fideos en caldo, huevo pelado encima y cebollita.',
 580, 72, 48, 10, 3, 820,
 '["recovery","high-protein","post-race","comfort"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/2664216/pexels-photo-2664216.jpeg', true),

(NULL, 'Curry japonés con arroz / Japanese Curry with Rice', 'Curry japonés con arroz', 'Japanese Curry with Rice', 'japanese',
 'Curry suave japonés con verduras y arroz | Mild Japanese curry with vegetables and rice',
 'dinner', 15, 30, 2,
 '[{"name":"arroz blanco / white rice","quantity":180,"unit":"g","calories":234,"protein":4,"carbs":52,"fat":0},{"name":"pollo / chicken","quantity":150,"unit":"g","calories":247,"protein":46,"carbs":0,"fat":5},{"name":"zanahoria / carrot","quantity":80,"unit":"g","calories":33,"protein":1,"carbs":8,"fat":0},{"name":"papa / potato","quantity":100,"unit":"g","calories":77,"protein":2,"carbs":17,"fat":0},{"name":"cebolla / onion","quantity":70,"unit":"g","calories":28,"protein":1,"carbs":7,"fat":0},{"name":"roux de curry / curry roux","quantity":40,"unit":"g","calories":170,"protein":2,"carbs":18,"fat":10}]',
 '1. Saltear cebolla, zanahoria y papa. 2. Agregar pollo y dorar. 3. Añadir agua y cocinar 15 min. 4. Disolver roux de curry y cocinar 5 min más. 5. Servir sobre arroz.',
 720, 88, 52, 12, 5, 680,
 '["carb-loading","dinner","pre-race"]', '["runners","cyclists","swimmers"]',
 'https://images.pexels.com/photos/7363753/pexels-photo-7363753.jpeg', true),

-- KOREAN
(NULL, 'Bibimbap de atletismo / Athlete Bibimbap', 'Bibimbap de atletismo', 'Athlete Bibimbap', 'korean',
 'Tazón coreano con arroz, verduras y proteína | Korean rice bowl with vegetables and protein',
 'lunch', 20, 25, 1,
 '[{"name":"arroz integral / brown rice","quantity":180,"unit":"g","calories":216,"protein":5,"carbs":45,"fat":2},{"name":"carne molida / ground beef","quantity":120,"unit":"g","calories":240,"protein":24,"carbs":0,"fat":16},{"name":"espinaca / spinach","quantity":80,"unit":"g","calories":18,"protein":2,"carbs":3,"fat":0},{"name":"zanahoria / carrot","quantity":50,"unit":"g","calories":21,"protein":0,"carbs":5,"fat":0},{"name":"brotes de soja / bean sprouts","quantity":50,"unit":"g","calories":15,"protein":1,"carbs":2,"fat":0},{"name":"huevo frito / fried egg","quantity":1,"unit":"unidad","calories":90,"protein":6,"carbs":0,"fat":7},{"name":"gochujang","quantity":15,"unit":"g","calories":30,"protein":1,"carbs":6,"fat":0}]',
 '1. Cocinar arroz integral. 2. Saltear carne con ajo y soja. 3. Blanquear espinaca y saltear zanahoria y brotes. 4. Colocar todo sobre arroz. 5. Freír huevo y poner encima. 6. Mezclar con gochujang.',
 630, 61, 38, 20, 6, 720,
 '["balanced","high-protein","korean","post-workout"]', '["runners","triathletes","cyclists"]',
 'https://images.pexels.com/photos/2098085/pexels-photo-2098085.jpeg', true),

(NULL, 'Dosirak de arroz y verduras / Rice Box Dosirak', 'Dosirak de arroz y verduras', 'Rice Box Dosirak', 'korean',
 'Lonchera coreana de arroz con proteína y banchan | Korean rice lunchbox with protein and side dishes',
 'lunch', 20, 20, 1,
 '[{"name":"arroz blanco / white rice","quantity":200,"unit":"g","calories":260,"protein":5,"carbs":57,"fat":0},{"name":"atún en lata / canned tuna","quantity":100,"unit":"g","calories":116,"protein":26,"carbs":0,"fat":1},{"name":"kimchi","quantity":60,"unit":"g","calories":15,"protein":1,"carbs":3,"fat":0},{"name":"huevo revuelto / scrambled egg","quantity":2,"unit":"unidad","calories":140,"protein":12,"carbs":1,"fat":10},{"name":"algas nori / nori seaweed","quantity":5,"unit":"g","calories":10,"protein":1,"carbs":1,"fat":0}]',
 '1. Cocinar arroz. 2. Mezclar atún con cebollita y mayonesa ligera. 3. Preparar huevos revueltos. 4. Organizar en lonchera con kimchi y algas. 5. Llevar como snack deportivo.',
 541, 62, 45, 11, 2, 850,
 '["portable","lunch","high-protein"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg', true),

-- CHINESE
(NULL, 'Congee de arroz con pollo / Chicken Rice Congee', 'Congee de arroz con pollo', 'Chicken Rice Congee', 'chinese',
 'Gachas suaves de arroz chino con pollo, perfectas post-carrera | Soft Chinese rice porridge with chicken, perfect post-race',
 'recovery', 10, 45, 2,
 '[{"name":"arroz / rice","quantity":100,"unit":"g","calories":130,"protein":3,"carbs":29,"fat":0},{"name":"caldo de pollo / chicken broth","quantity":800,"unit":"ml","calories":32,"protein":4,"carbs":4,"fat":0},{"name":"pechuga de pollo / chicken breast","quantity":120,"unit":"g","calories":198,"protein":37,"carbs":0,"fat":4},{"name":"jengibre / ginger","quantity":10,"unit":"g","calories":8,"protein":0,"carbs":2,"fat":0},{"name":"cebollita / green onion","quantity":15,"unit":"g","calories":5,"protein":0,"carbs":1,"fat":0},{"name":"salsa de soja / soy sauce","quantity":10,"unit":"ml","calories":6,"protein":1,"carbs":1,"fat":0}]',
 '1. Hervir arroz en caldo con jengibre por 45 min removiendo. 2. Desmenuzar pollo cocido. 3. Agregar pollo al congee. 4. Servir con cebollita y soja.',
 379, 37, 44, 4, 1, 690,
 '["recovery","easy-digest","post-race","high-protein"]', '["runners","cyclists","triathletes","swimmers"]',
 'https://images.pexels.com/photos/3026804/pexels-photo-3026804.jpeg', true),

(NULL, 'Arroz frito de entrenamiento / Training Fried Rice', 'Arroz frito de entrenamiento', 'Training Fried Rice', 'chinese',
 'Arroz frito proteico con huevo, verduras y pollo | Protein-packed fried rice with egg, vegetables and chicken',
 'lunch', 10, 15, 1,
 '[{"name":"arroz cocido / cooked rice","quantity":200,"unit":"g","calories":260,"protein":5,"carbs":57,"fat":0},{"name":"pollo / chicken","quantity":100,"unit":"g","calories":165,"protein":31,"carbs":0,"fat":4},{"name":"huevo / egg","quantity":2,"unit":"unidad","calories":155,"protein":13,"carbs":1,"fat":11},{"name":"arvejas / peas","quantity":50,"unit":"g","calories":42,"protein":3,"carbs":8,"fat":0},{"name":"zanahoria / carrot","quantity":40,"unit":"g","calories":16,"protein":0,"carbs":4,"fat":0},{"name":"salsa de soja / soy sauce","quantity":15,"unit":"ml","calories":9,"protein":1,"carbs":1,"fat":0},{"name":"aceite de sésamo / sesame oil","quantity":5,"unit":"ml","calories":45,"protein":0,"carbs":0,"fat":5}]',
 '1. Calentar wok o sartén grande. 2. Saltear pollo. 3. Agregar verduras y saltear 2 min. 4. Hacer huevo revuelto en el centro. 5. Agregar arroz frío y mezclar. 6. Condimentar con soja y sésamo.',
 692, 72, 53, 17, 4, 780,
 '["high-protein","lunch","stir-fry"]', '["runners","cyclists","swimmers"]',
 'https://images.pexels.com/photos/1410235/pexels-photo-1410235.jpeg', true),

-- THAI
(NULL, 'Pad Thai de camarón / Shrimp Pad Thai', 'Pad Thai de camarón', 'Shrimp Pad Thai', 'thai',
 'Fideos de arroz con camarón, tofu y maní, clásico tailandés | Rice noodles with shrimp, tofu and peanuts, Thai classic',
 'dinner', 15, 20, 1,
 '[{"name":"fideos de arroz / rice noodles","quantity":100,"unit":"g","calories":192,"protein":2,"carbs":45,"fat":0},{"name":"camarones / shrimp","quantity":120,"unit":"g","calories":101,"protein":21,"carbs":1,"fat":1},{"name":"tofu firme / firm tofu","quantity":80,"unit":"g","calories":62,"protein":7,"carbs":2,"fat":3},{"name":"huevo / egg","quantity":1,"unit":"unidad","calories":78,"protein":6,"carbs":0,"fat":5},{"name":"brotes de soja / bean sprouts","quantity":60,"unit":"g","calories":18,"protein":2,"carbs":2,"fat":0},{"name":"maní / peanuts","quantity":20,"unit":"g","calories":113,"protein":5,"carbs":3,"fat":10},{"name":"salsa de tamarindo / tamarind sauce","quantity":25,"unit":"ml","calories":45,"protein":0,"carbs":12,"fat":0}]',
 '1. Remojar fideos en agua tibia 20 min. 2. Saltear camarón y tofu en wok. 3. Agregar fideos escurridos. 4. Hacer huevo al costado. 5. Condimentar con tamarindo, pescado y azúcar. 6. Servir con maní y lima.',
 609, 65, 43, 19, 3, 860,
 '["dinner","high-protein","thai-classic"]', '["runners","triathletes","swimmers"]',
 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg', true),

(NULL, 'Arroz con leche de coco tailandés / Thai Coconut Rice', 'Arroz con leche de coco tailandés', 'Thai Coconut Rice', 'thai',
 'Arroz pegajoso con leche de coco, plátano y semillas | Sticky rice with coconut milk, banana and seeds',
 'snack', 5, 20, 1,
 '[{"name":"arroz jazmín / jasmine rice","quantity":150,"unit":"g","calories":195,"protein":3,"carbs":43,"fat":0},{"name":"leche de coco / coconut milk","quantity":120,"unit":"ml","calories":150,"protein":2,"carbs":4,"fat":15},{"name":"plátano / banana","quantity":1,"unit":"mediano","calories":89,"protein":1,"carbs":23,"fat":0},{"name":"semillas de sésamo / sesame seeds","quantity":10,"unit":"g","calories":56,"protein":2,"carbs":2,"fat":5},{"name":"miel / honey","quantity":15,"unit":"ml","calories":45,"protein":0,"carbs":12,"fat":0}]',
 '1. Cocinar arroz con leche de coco y pizca de sal. 2. Remover hasta cremoso. 3. Servir tibio. 4. Cubrir con plátano en rodajas, sésamo y miel.',
 535, 84, 8, 20, 3, 120,
 '["pre-race","carb-loading","sweet","snack"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/1633578/pexels-photo-1633578.jpeg', true),

-- VIETNAMESE
(NULL, 'Pho de res / Beef Pho', 'Pho de res', 'Beef Pho', 'vietnamese',
 'Reconfortante sopa vietnamita de fideos con res y hierbas | Comforting Vietnamese noodle soup with beef and herbs',
 'recovery', 15, 30, 1,
 '[{"name":"fideos de arroz anchos / wide rice noodles","quantity":120,"unit":"g","calories":231,"protein":4,"carbs":53,"fat":0},{"name":"res en láminas / sliced beef","quantity":120,"unit":"g","calories":228,"protein":26,"carbs":0,"fat":14},{"name":"caldo de res / beef broth","quantity":600,"unit":"ml","calories":36,"protein":6,"carbs":2,"fat":1},{"name":"albahaca tailandesa / thai basil","quantity":10,"unit":"g","calories":3,"protein":0,"carbs":0,"fat":0},{"name":"lima / lime","quantity":1,"unit":"unidad","calories":20,"protein":0,"carbs":7,"fat":0},{"name":"brotes de soja / bean sprouts","quantity":50,"unit":"g","calories":15,"protein":1,"carbs":2,"fat":0},{"name":"salsa hoisin / hoisin sauce","quantity":10,"unit":"ml","calories":35,"protein":1,"carbs":7,"fat":1}]',
 '1. Hervir caldo con especias (estrella de anís, canela). 2. Cocinar fideos aparte. 3. Colocar fideos en bowl. 4. Verter caldo caliente sobre res en láminas. 5. Servir con brotes, albahaca, lima y hoisin.',
 568, 69, 38, 16, 3, 1050,
 '["recovery","comfort","post-race","high-protein"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/4069383/pexels-photo-4069383.jpeg', true),

(NULL, 'Bánh mì deportivo / Athlete Banh Mi', 'Bánh mì deportivo', 'Athlete Banh Mi', 'vietnamese',
 'Sándwich vietnamita con pollo, verduras pickled y hierbas | Vietnamese sandwich with chicken, pickled vegetables and herbs',
 'lunch', 15, 10, 1,
 '[{"name":"baguette pequeña / small baguette","quantity":100,"unit":"g","calories":264,"protein":9,"carbs":52,"fat":2},{"name":"pollo a la plancha / grilled chicken","quantity":100,"unit":"g","calories":165,"protein":31,"carbs":0,"fat":4},{"name":"zanahoria y daikon pickled","quantity":60,"unit":"g","calories":20,"protein":1,"carbs":4,"fat":0},{"name":"pepino / cucumber","quantity":40,"unit":"g","calories":6,"protein":0,"carbs":1,"fat":0},{"name":"cilantro / cilantro","quantity":10,"unit":"g","calories":2,"protein":0,"carbs":0,"fat":0},{"name":"mayonesa / mayonnaise","quantity":15,"unit":"g","calories":100,"protein":0,"carbs":0,"fat":11}]',
 '1. Preparar zanahoria y daikon pickled con vinagre, sal y azúcar. 2. Tostar baguette. 3. Untar con mayonesa y salsa sriracha. 4. Rellenar con pollo, verduras pickled, pepino y cilantro.',
 557, 58, 41, 17, 3, 720,
 '["portable","lunch","balanced","high-protein"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/1640773/pexels-photo-1640773.jpeg', true),

-- INDONESIAN / MALAY
(NULL, 'Nasi goreng deportivo / Athlete Nasi Goreng', 'Nasi goreng deportivo', 'Athlete Nasi Goreng', 'indonesian',
 'Arroz frito indonesio con huevo, pollo y verduras | Indonesian fried rice with egg, chicken and vegetables',
 'lunch', 10, 15, 1,
 '[{"name":"arroz cocido / cooked rice","quantity":200,"unit":"g","calories":260,"protein":5,"carbs":57,"fat":0},{"name":"pollo / chicken","quantity":100,"unit":"g","calories":165,"protein":31,"carbs":0,"fat":4},{"name":"huevo frito / fried egg","quantity":1,"unit":"unidad","calories":90,"protein":6,"carbs":0,"fat":7},{"name":"repollo / cabbage","quantity":50,"unit":"g","calories":12,"protein":1,"carbs":3,"fat":0},{"name":"kecap manis","quantity":20,"unit":"ml","calories":40,"protein":1,"carbs":10,"fat":0},{"name":"sambal","quantity":10,"unit":"g","calories":12,"protein":0,"carbs":2,"fat":0}]',
 '1. Saltear ajo y chalota en aceite. 2. Agregar pollo picado y cocinar. 3. Agregar arroz frío y revolver. 4. Condimentar con kecap manis y sambal. 5. Hacer pozo y cocinar huevo. 6. Servir con rodajas de pepino.',
 579, 71, 43, 11, 3, 680,
 '["lunch","high-protein","asian-classic","fried-rice"]', '["runners","cyclists","swimmers"]',
 'https://images.pexels.com/photos/723198/pexels-photo-723198.jpeg', true),

-- SRI LANKAN
(NULL, 'Arroz con curry cingalés / Sri Lankan Curry Rice', 'Arroz con curry cingalés', 'Sri Lankan Curry Rice', 'sri_lankan',
 'Arroz con curry de coco y lentejas, rico en carbohidratos | Rice with coconut curry and lentils, carb-rich',
 'dinner', 15, 35, 2,
 '[{"name":"arroz rojo de Sri Lanka / red rice","quantity":180,"unit":"g","calories":234,"protein":5,"carbs":52,"fat":1},{"name":"lentejas rojas / red lentils","quantity":100,"unit":"g","calories":116,"protein":9,"carbs":20,"fat":0},{"name":"leche de coco / coconut milk","quantity":200,"unit":"ml","calories":230,"protein":2,"carbs":6,"fat":24},{"name":"cúrcuma / turmeric","quantity":5,"unit":"g","calories":16,"protein":0,"carbs":3,"fat":0},{"name":"hojas de curry / curry leaves","quantity":10,"unit":"g","calories":5,"protein":0,"carbs":1,"fat":0},{"name":"cebolla / onion","quantity":70,"unit":"g","calories":28,"protein":1,"carbs":7,"fat":0}]',
 '1. Cocinar arroz rojo. 2. Sofreír cebolla con hojas de curry y cúrcuma. 3. Agregar lentejas y leche de coco. 4. Cocinar 20 min hasta espeso. 5. Servir curry sobre arroz.',
 629, 82, 17, 25, 8, 380,
 '["dinner","carb-loading","plant-based","pre-race"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg', true),

-- SCANDINAVIAN
(NULL, 'Gachas de avena nórdica / Nordic Oat Porridge', 'Gachas de avena nórdica', 'Nordic Oat Porridge', 'scandinavian',
 'Avena cremosa con frutos del bosque y semillas, estilo escandinavo | Creamy oats with berries and seeds, Scandinavian style',
 'breakfast', 5, 10, 1,
 '[{"name":"avena / rolled oats","quantity":80,"unit":"g","calories":296,"protein":10,"carbs":54,"fat":6},{"name":"leche / milk","quantity":200,"unit":"ml","calories":122,"protein":6,"carbs":9,"fat":6},{"name":"arándanos / blueberries","quantity":80,"unit":"g","calories":46,"protein":1,"carbs":11,"fat":0},{"name":"semillas de linaza / flaxseeds","quantity":10,"unit":"g","calories":55,"protein":2,"carbs":3,"fat":4},{"name":"semillas de calabaza / pumpkin seeds","quantity":15,"unit":"g","calories":83,"protein":4,"carbs":2,"fat":7},{"name":"miel / honey","quantity":15,"unit":"ml","calories":45,"protein":0,"carbs":12,"fat":0}]',
 '1. Hervir leche, agregar avena y cocinar 5-7 min removiendo. 2. Añadir pizca de sal y canela. 3. Servir en bowl. 4. Cubrir con arándanos, linaza, calabaza y miel.',
 647, 91, 23, 23, 9, 95,
 '["breakfast","pre-race","nordic","berries","high-fiber"]', '["runners","cyclists","skiers","triathletes"]',
 'https://images.pexels.com/photos/1510701/pexels-photo-1510701.jpeg', true),

(NULL, 'Pan de centeno con salmón / Rye Bread Salmon', 'Pan de centeno con salmón ahumado', 'Smoked Salmon Rye Bread', 'scandinavian',
 'Pan de centeno escandinavo con salmón ahumado, queso y pepino | Scandinavian rye bread with smoked salmon, cheese and cucumber',
 'breakfast', 5, 0, 1,
 '[{"name":"pan de centeno / rye bread","quantity":80,"unit":"g","calories":184,"protein":6,"carbs":36,"fat":2},{"name":"salmón ahumado / smoked salmon","quantity":80,"unit":"g","calories":117,"protein":18,"carbs":0,"fat":5},{"name":"queso crema / cream cheese","quantity":30,"unit":"g","calories":90,"protein":2,"carbs":1,"fat":9},{"name":"pepino / cucumber","quantity":40,"unit":"g","calories":6,"protein":0,"carbs":1,"fat":0},{"name":"eneldo / dill","quantity":5,"unit":"g","calories":2,"protein":0,"carbs":0,"fat":0},{"name":"alcaparras / capers","quantity":10,"unit":"g","calories":2,"protein":0,"carbs":0,"fat":0}]',
 '1. Untar queso crema sobre pan de centeno. 2. Colocar salmón ahumado. 3. Agregar rodajas de pepino. 4. Decorar con eneldo y alcaparras. 5. Exprimir un poco de limón.',
 401, 38, 26, 16, 5, 890,
 '["breakfast","omega3","quick","no-cook"]', '["runners","cyclists","triathletes","swimmers"]',
 'https://images.pexels.com/photos/1640771/pexels-photo-1640771.jpeg', true),

(NULL, 'Sopa de remolacha nórdica / Nordic Beetroot Soup', 'Sopa de remolacha nórdica', 'Nordic Beetroot Soup', 'scandinavian',
 'Sopa espesa de remolacha con yogur, ideal para corredores por sus nitratos | Thick beet soup with yogurt, ideal for runners for its nitrates',
 'lunch', 10, 30, 2,
 '[{"name":"remolacha / beet","quantity":300,"unit":"g","calories":129,"protein":5,"carbs":29,"fat":0},{"name":"caldo de verduras / vegetable broth","quantity":500,"unit":"ml","calories":20,"protein":1,"carbs":4,"fat":0},{"name":"cebolla / onion","quantity":80,"unit":"g","calories":32,"protein":1,"carbs":7,"fat":0},{"name":"yogur griego / Greek yogurt","quantity":60,"unit":"g","calories":58,"protein":9,"carbs":3,"fat":1},{"name":"eneldo / dill","quantity":5,"unit":"g","calories":2,"protein":0,"carbs":0,"fat":0},{"name":"vinagre de manzana / apple cider vinegar","quantity":10,"unit":"ml","calories":2,"protein":0,"carbs":0,"fat":0}]',
 '1. Cocinar remolacha y cebolla en caldo 25 min. 2. Licuar hasta suave. 3. Salpimentar y añadir vinagre. 4. Servir con cucharada de yogur y eneldo fresco.',
 243, 46, 16, 2, 7, 420,
 '["performance","nitrates","soup","pre-race","plant-based"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/3297948/pexels-photo-3297948.jpeg', true),

-- CARIBBEAN
(NULL, 'Arroz con gandules caribeño / Caribbean Rice with Pigeon Peas', 'Arroz con gandules caribeño', 'Caribbean Rice with Pigeon Peas', 'caribbean',
 'Clásico arroz puertorriqueño/caribeño con gandules y pollo | Classic Caribbean rice with pigeon peas and chicken',
 'dinner', 15, 35, 2,
 '[{"name":"arroz de grano largo / long grain rice","quantity":200,"unit":"g","calories":260,"protein":5,"carbs":57,"fat":0},{"name":"gandules / pigeon peas","quantity":100,"unit":"g","calories":120,"protein":8,"carbs":21,"fat":0},{"name":"pollo / chicken","quantity":150,"unit":"g","calories":247,"protein":46,"carbs":0,"fat":5},{"name":"sofrito","quantity":30,"unit":"g","calories":20,"protein":0,"carbs":4,"fat":0},{"name":"tomate / tomato","quantity":80,"unit":"g","calories":14,"protein":1,"carbs":3,"fat":0},{"name":"aceite de oliva / olive oil","quantity":10,"unit":"ml","calories":88,"protein":0,"carbs":0,"fat":10}]',
 '1. Sofreír sofrito en aceite. 2. Agregar pollo trozado y dorar. 3. Añadir tomate y gandules. 4. Agregar arroz y agua caliente. 5. Cocinar a fuego bajo 20 min tapado.',
 749, 85, 60, 15, 8, 580,
 '["dinner","carb-loading","caribbean","high-protein"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/1640775/pexels-photo-1640775.jpeg', true),

(NULL, 'Batata caribeña con frijoles negros / Caribbean Sweet Potato Black Beans', 'Batata caribeña con frijoles negros', 'Caribbean Sweet Potato Black Beans', 'caribbean',
 'Batata asada rellena de frijoles negros con especias caribeñas | Roasted sweet potato stuffed with Caribbean-spiced black beans',
 'lunch', 10, 40, 1,
 '[{"name":"batata grande / large sweet potato","quantity":200,"unit":"g","calories":172,"protein":4,"carbs":40,"fat":0},{"name":"frijoles negros / black beans","quantity":120,"unit":"g","calories":160,"protein":11,"carbs":29,"fat":1},{"name":"pimiento / bell pepper","quantity":60,"unit":"g","calories":19,"protein":1,"carbs":4,"fat":0},{"name":"comino / cumin","quantity":3,"unit":"g","calories":8,"protein":0,"carbs":1,"fat":0},{"name":"jugo de lima / lime juice","quantity":15,"unit":"ml","calories":4,"protein":0,"carbs":1,"fat":0},{"name":"cilantro / cilantro","quantity":10,"unit":"g","calories":2,"protein":0,"carbs":0,"fat":0}]',
 '1. Asar batata 35-40 min a 200°C. 2. Calentar frijoles con pimiento, comino y ajo. 3. Abrir batata y rellenar con mezcla de frijoles. 4. Coronar con cilantro y lima.',
 365, 75, 16, 1, 12, 290,
 '["lunch","plant-based","pre-race","high-fiber"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/5835353/pexels-photo-5835353.jpeg', true),

-- CENTRAL AMERICAN
(NULL, 'Gallo pinto costarricense / Costa Rican Gallo Pinto', 'Gallo pinto costarricense', 'Costa Rican Gallo Pinto', 'central_american',
 'Desayuno costarricense de arroz y frijoles negros con huevo | Costa Rican breakfast of rice and black beans with egg',
 'breakfast', 10, 20, 1,
 '[{"name":"arroz blanco cocido / cooked white rice","quantity":150,"unit":"g","calories":195,"protein":4,"carbs":43,"fat":0},{"name":"frijoles negros / black beans","quantity":120,"unit":"g","calories":160,"protein":11,"carbs":29,"fat":1},{"name":"huevo revuelto / scrambled eggs","quantity":2,"unit":"unidad","calories":140,"protein":12,"carbs":1,"fat":10},{"name":"salsa Lizano","quantity":20,"unit":"ml","calories":15,"protein":0,"carbs":4,"fat":0},{"name":"cebolla / onion","quantity":40,"unit":"g","calories":16,"protein":0,"carbs":4,"fat":0},{"name":"pimiento / bell pepper","quantity":30,"unit":"g","calories":9,"protein":0,"carbs":2,"fat":0}]',
 '1. Sofreír cebolla y pimiento. 2. Agregar frijoles negros cocidos. 3. Añadir arroz y mezclar bien. 4. Condimentar con salsa Lizano. 5. Servir con huevos revueltos al costado.',
 535, 83, 27, 11, 10, 520,
 '["breakfast","carb-rich","complete-protein","central-american"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/8500349/pexels-photo-8500349.jpeg', true),

-- RUSSIAN / EASTERN EUROPEAN
(NULL, 'Gachas de trigo sarraceno / Buckwheat Kasha', 'Gachas de trigo sarraceno', 'Buckwheat Kasha', 'eastern_european',
 'Gachas rusas de trigo sarraceno con mantequilla y huevo, alto en proteína | Russian buckwheat porridge with butter and egg, high protein',
 'breakfast', 5, 20, 1,
 '[{"name":"trigo sarraceno / buckwheat","quantity":100,"unit":"g","calories":343,"protein":13,"carbs":72,"fat":3},{"name":"huevo / egg","quantity":2,"unit":"unidad","calories":155,"protein":13,"carbs":1,"fat":11},{"name":"mantequilla / butter","quantity":10,"unit":"g","calories":72,"protein":0,"carbs":0,"fat":8},{"name":"cebolla / onion","quantity":50,"unit":"g","calories":20,"protein":1,"carbs":5,"fat":0},{"name":"sal / salt","quantity":2,"unit":"g","calories":0,"protein":0,"carbs":0,"fat":0}]',
 '1. Tostar trigo sarraceno en seco 2 min. 2. Hervir con agua 2:1 por 15 min. 3. Sofreír cebolla en mantequilla. 4. Mezclar cebolla con gachas. 5. Servir con huevos duros o revueltos encima.',
 590, 78, 27, 22, 8, 150,
 '["breakfast","pre-race","eastern-european","high-fiber"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg', true),

(NULL, 'Borscht de remolacha / Beet Borscht', 'Borscht de remolacha', 'Beet Borscht', 'eastern_european',
 'Sopa rusa/ucraniana de remolacha con crema agria, rica en nitratos | Russian/Ukrainian beet soup with sour cream, rich in nitrates',
 'lunch', 15, 40, 2,
 '[{"name":"remolacha / beet","quantity":250,"unit":"g","calories":108,"protein":4,"carbs":24,"fat":0},{"name":"repollo / cabbage","quantity":150,"unit":"g","calories":36,"protein":2,"carbs":8,"fat":0},{"name":"papa / potato","quantity":100,"unit":"g","calories":77,"protein":2,"carbs":17,"fat":0},{"name":"zanahoria / carrot","quantity":80,"unit":"g","calories":33,"protein":1,"carbs":8,"fat":0},{"name":"caldo de res / beef broth","quantity":600,"unit":"ml","calories":36,"protein":6,"carbs":2,"fat":1},{"name":"crema agria / sour cream","quantity":30,"unit":"g","calories":57,"protein":1,"carbs":1,"fat":6}]',
 '1. Rallar remolacha, picar repollo, papa y zanahoria. 2. Sofreír zanahoria y remolacha 5 min. 3. Agregar caldo, papa y repollo. 4. Cocinar 30 min. 5. Servir con cucharada de crema agria.',
 347, 60, 16, 7, 10, 680,
 '["lunch","nitrates","performance","soup","pre-race"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/5409010/pexels-photo-5409010.jpeg', true),

(NULL, 'Golubtsy - Rollitos de repollo rellenos / Stuffed Cabbage Rolls', 'Golubtsy - Rollitos de repollo', 'Stuffed Cabbage Rolls', 'eastern_european',
 'Rollitos de repollo rellenos de carne y arroz al estilo ruso | Cabbage rolls stuffed with meat and rice Russian style',
 'dinner', 25, 45, 2,
 '[{"name":"hojas de repollo / cabbage leaves","quantity":200,"unit":"g","calories":50,"protein":2,"carbs":11,"fat":0},{"name":"carne molida de res / ground beef","quantity":200,"unit":"g","calories":400,"protein":28,"carbs":0,"fat":32},{"name":"arroz / rice","quantity":80,"unit":"g","calories":104,"protein":2,"carbs":23,"fat":0},{"name":"tomate triturado / crushed tomato","quantity":200,"unit":"g","calories":40,"protein":2,"carbs":8,"fat":0},{"name":"cebolla / onion","quantity":60,"unit":"g","calories":24,"protein":1,"carbs":6,"fat":0},{"name":"crema agria / sour cream","quantity":30,"unit":"g","calories":57,"protein":1,"carbs":1,"fat":6}]',
 '1. Blanquear hojas de repollo. 2. Mezclar carne con arroz cocido, cebolla y condimentos. 3. Rellenar hojas y doblar. 4. Colocar en fuente con tomate triturado. 5. Hornear 45 min a 180°C. 6. Servir con crema agria.',
 675, 43, 34, 38, 7, 520,
 '["dinner","high-protein","eastern-european","comfort"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/2233729/pexels-photo-2233729.jpeg', true),

-- SOUTH AFRICAN
(NULL, 'Bobotie sudafricano / South African Bobotie', 'Bobotie sudafricano', 'South African Bobotie', 'south_african',
 'Pastel de carne especiado sudafricano con cúrcuma y huevo | Spiced South African meat pie with turmeric and egg',
 'dinner', 20, 40, 2,
 '[{"name":"carne molida / ground beef","quantity":250,"unit":"g","calories":500,"protein":35,"carbs":0,"fat":40},{"name":"cebolla / onion","quantity":80,"unit":"g","calories":32,"protein":1,"carbs":7,"fat":0},{"name":"pan / bread","quantity":40,"unit":"g","calories":106,"protein":3,"carbs":20,"fat":1},{"name":"leche / milk","quantity":120,"unit":"ml","calories":73,"protein":4,"carbs":6,"fat":4},{"name":"huevo / egg","quantity":2,"unit":"unidad","calories":155,"protein":13,"carbs":1,"fat":11},{"name":"curry en polvo / curry powder","quantity":10,"unit":"g","calories":32,"protein":1,"carbs":6,"fat":1},{"name":"pasas / raisins","quantity":30,"unit":"g","calories":90,"protein":1,"carbs":22,"fat":0}]',
 '1. Remojar pan en leche, exprimir. 2. Sofreír cebolla con curry. 3. Mezclar carne, pan, cebolla, pasas y especias. 4. Colocar en fuente, hornear 30 min a 180°C. 5. Batir huevos con leche, verter encima. 6. Hornear 10 min más.',
 988, 56, 54, 52, 3, 680,
 '["dinner","south-african","high-protein","traditional"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/1640776/pexels-photo-1640776.jpeg', true),

(NULL, 'Pap y chakalaka / Pap and Chakalaka', 'Pap y chakalaka', 'Pap and Chakalaka', 'south_african',
 'Gachas de maíz sudafricanas con chakalaka picante de verduras | South African corn porridge with spicy vegetable chakalaka',
 'dinner', 10, 25, 2,
 '[{"name":"harina de maíz / corn meal","quantity":150,"unit":"g","calories":543,"protein":12,"carbs":115,"unit2":"g"},{"name":"tomate / tomato","quantity":100,"unit":"g","calories":18,"protein":1,"carbs":4,"fat":0},{"name":"pimiento / bell pepper","quantity":80,"unit":"g","calories":25,"protein":1,"carbs":5,"fat":0},{"name":"frijoles / beans","quantity":100,"unit":"g","calories":127,"protein":9,"carbs":22,"fat":1},{"name":"cebolla / onion","quantity":60,"unit":"g","calories":24,"protein":1,"carbs":6,"fat":0},{"name":"curry en polvo / curry powder","quantity":5,"unit":"g","calories":16,"protein":1,"carbs":3,"fat":0}]',
 '1. Hacer pap: hervir agua con sal, agregar harina de maíz gradualmente, cocinar 20 min revolviendo. 2. Para chakalaka: sofreír cebolla, pimiento con curry. 3. Agregar tomate y frijoles. 4. Cocinar 10 min. 5. Servir pap con chakalaka encima.',
 753, 150, 24, 2, 14, 580,
 '["dinner","carb-loading","plant-based","south-african"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/5409010/pexels-photo-5409010.jpeg', true),

-- NORTH AFRICAN - MORE
(NULL, 'Msemen marroquí con miel / Moroccan Msemen with Honey', 'Msemen marroquí con miel y mantequilla', 'Moroccan Msemen with Honey and Butter', 'north_african',
 'Crepes hojaldradas marroquíes con miel y mantequilla, energía rápida | Moroccan flaky crepes with honey and butter, quick energy',
 'breakfast', 15, 20, 2,
 '[{"name":"harina / flour","quantity":200,"unit":"g","calories":728,"protein":20,"carbs":152,"fat":2},{"name":"semolina","quantity":50,"unit":"g","calories":175,"protein":6,"carbs":35,"fat":1},{"name":"mantequilla / butter","quantity":30,"unit":"g","calories":216,"protein":0,"carbs":0,"fat":24},{"name":"miel / honey","quantity":40,"unit":"ml","calories":120,"protein":0,"carbs":33,"fat":0}]',
 '1. Mezclar harinas con agua tibia y sal hasta masa suave. 2. Reposar 30 min. 3. Estirar fino, plegar con mantequilla varias veces. 4. Cocinar en sartén 3 min cada lado. 5. Servir caliente con miel y mantequilla.',
 1239, 220, 26, 27, 5, 320,
 '["breakfast","pre-race","energy","north-african","sweet"]', '["runners","cyclists"]',
 'https://images.pexels.com/photos/1640778/pexels-photo-1640778.jpeg', true),

(NULL, 'Shakshuka de tomatillo / Green Shakshuka', 'Shakshuka verde de tomatillo', 'Green Shakshuka Tomatillo', 'north_african',
 'Huevos pochados en salsa verde de tomatillo, jalapeño y espinaca | Poached eggs in green tomatillo, jalapeño and spinach sauce',
 'breakfast', 10, 20, 1,
 '[{"name":"huevos / eggs","quantity":3,"unit":"unidad","calories":233,"protein":19,"carbs":1,"fat":16},{"name":"espinaca / spinach","quantity":100,"unit":"g","calories":23,"protein":3,"carbs":4,"fat":0},{"name":"tomatillos","quantity":150,"unit":"g","calories":48,"protein":1,"carbs":9,"fat":1},{"name":"jalapeño","quantity":20,"unit":"g","calories":6,"protein":0,"carbs":1,"fat":0},{"name":"cebolla / onion","quantity":60,"unit":"g","calories":24,"protein":1,"carbs":6,"fat":0},{"name":"aceite de oliva / olive oil","quantity":10,"unit":"ml","calories":88,"protein":0,"carbs":0,"fat":10},{"name":"pan pita","quantity":60,"unit":"g","calories":165,"protein":5,"carbs":33,"fat":1}]',
 '1. Licuar tomatillo, jalapeño y cebolla. 2. Sofreír la mezcla en aceite 5 min. 3. Agregar espinaca. 4. Hacer pozos y romper huevos. 5. Tapar y cocinar 8 min. 6. Servir con pita.',
 587, 54, 29, 28, 6, 480,
 '["breakfast","high-protein","plant-rich","eggs"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/4721265/pexels-photo-4721265.jpeg', true),

-- MIDDLE EASTERN - MORE
(NULL, 'Mansaf de cordero / Lamb Mansaf', 'Mansaf de cordero con arroz', 'Lamb Mansaf with Rice', 'middle_eastern',
 'Plato nacional jordano de cordero con salsa de yogur fermentado sobre arroz | Jordanian national dish of lamb with fermented yogurt sauce over rice',
 'dinner', 20, 60, 2,
 '[{"name":"pierna de cordero / lamb leg","quantity":200,"unit":"g","calories":294,"protein":28,"carbs":0,"fat":20},{"name":"arroz basmati / basmati rice","quantity":200,"unit":"g","calories":260,"protein":5,"carbs":57,"fat":0},{"name":"yogur fermentado / jameed yogurt","quantity":150,"unit":"g","calories":120,"protein":8,"carbs":10,"fat":5},{"name":"almendras / almonds","quantity":30,"unit":"g","calories":174,"protein":6,"carbs":6,"fat":15},{"name":"piñones / pine nuts","quantity":20,"unit":"g","calories":135,"protein":4,"carbs":4,"fat":14},{"name":"cúrcuma y cardamomo","quantity":5,"unit":"g","calories":16,"protein":0,"carbs":3,"fat":0}]',
 '1. Cocer cordero en agua con especias 45 min. 2. Agregar yogur fermentado y cocinar 15 min. 3. Servir arroz en bandeja grande. 4. Colocar cordero encima. 5. Bañar con salsa de yogur. 6. Decorar con almendras y piñones tostados.',
 999, 67, 51, 54, 3, 720,
 '["dinner","high-protein","traditional","celebration"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg', true),

(NULL, 'Fattoush ensalada / Fattoush Salad', 'Fattoush - ensalada levantina', 'Fattoush - Levantine Salad', 'middle_eastern',
 'Ensalada fresca levantina con pan pita crocante, verduras y sumac | Fresh Levantine salad with crispy pita, vegetables and sumac',
 'lunch', 15, 10, 1,
 '[{"name":"lechuga romana / romaine lettuce","quantity":100,"unit":"g","calories":17,"protein":1,"carbs":3,"fat":0},{"name":"tomate / tomato","quantity":100,"unit":"g","calories":18,"protein":1,"carbs":4,"fat":0},{"name":"pepino / cucumber","quantity":80,"unit":"g","calories":11,"protein":1,"carbs":2,"fat":0},{"name":"rábano / radish","quantity":40,"unit":"g","calories":7,"protein":0,"carbs":2,"fat":0},{"name":"pan pita tostado / toasted pita","quantity":40,"unit":"g","calories":110,"protein":3,"carbs":22,"fat":1},{"name":"sumac","quantity":5,"unit":"g","calories":15,"protein":0,"carbs":3,"fat":0},{"name":"aceite de oliva / olive oil","quantity":15,"unit":"ml","calories":133,"protein":0,"carbs":0,"fat":15},{"name":"jugo de limón / lemon juice","quantity":20,"unit":"ml","calories":5,"protein":0,"carbs":2,"fat":0}]',
 '1. Cortar verduras en trozos. 2. Tostar pan pita en horno o sartén. 3. Mezclar verduras con sumac, aceite y limón. 4. Agregar pita roto encima antes de servir.',
 316, 38, 6, 16, 5, 320,
 '["lunch","salad","light","pre-workout","plant-based"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/1640772/pexels-photo-1640772.jpeg', true),

-- WEST AFRICAN - MORE
(NULL, 'Jollof rice ghanés / Ghanaian Jollof Rice', 'Jollof rice ghanés con pollo', 'Ghanaian Jollof Rice with Chicken', 'west_african',
 'El famoso arroz jollof de Ghana con pollo y verduras en salsa de tomate | Famous Ghanaian jollof rice with chicken and vegetables in tomato sauce',
 'dinner', 20, 45, 2,
 '[{"name":"arroz de grano largo / long grain rice","quantity":200,"unit":"g","calories":260,"protein":5,"carbs":57,"fat":0},{"name":"pollo muslo / chicken thigh","quantity":200,"unit":"g","calories":330,"protein":34,"carbs":0,"fat":22},{"name":"tomate triturado / crushed tomato","quantity":200,"unit":"g","calories":40,"protein":2,"carbs":8,"fat":0},{"name":"cebolla / onion","quantity":100,"unit":"g","calories":40,"protein":1,"carbs":9,"fat":0},{"name":"ajo / garlic","quantity":15,"unit":"g","calories":20,"protein":1,"carbs":5,"fat":0},{"name":"curry / curry powder","quantity":5,"unit":"g","calories":16,"protein":1,"carbs":3,"fat":0},{"name":"aceite de palma / palm oil","quantity":15,"unit":"ml","calories":133,"protein":0,"carbs":0,"fat":15}]',
 '1. Sofreír cebolla, ajo y tomate en aceite. 2. Agregar condimentos y pasta de tomate. 3. Dorar pollo en la mezcla. 4. Agregar arroz crudo y caldo. 5. Cocinar tapado a fuego bajo 25 min.',
 839, 74, 43, 37, 5, 680,
 '["dinner","carb-loading","west-african","jollof","high-protein"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/6152391/pexels-photo-6152391.jpeg', true),

(NULL, 'Fufu con sopa de maní / Fufu with Peanut Soup', 'Fufu con sopa de maní', 'Fufu with Peanut Soup', 'west_african',
 'Fufu de yuca con sopa energética de maní, alto en carbohidratos | Cassava fufu with energetic peanut soup, high in carbohydrates',
 'dinner', 20, 30, 2,
 '[{"name":"yuca / cassava","quantity":300,"unit":"g","calories":330,"protein":3,"carbs":78,"fat":0},{"name":"mantequilla de maní / peanut butter","quantity":60,"unit":"g","calories":360,"protein":14,"carbs":12,"fat":30},{"name":"pollo / chicken","quantity":150,"unit":"g","calories":247,"protein":46,"carbs":0,"fat":5},{"name":"tomate / tomato","quantity":100,"unit":"g","calories":18,"protein":1,"carbs":4,"fat":0},{"name":"cebolla / onion","quantity":60,"unit":"g","calories":24,"protein":1,"carbs":6,"fat":0},{"name":"dado de caldo / bouillon cube","quantity":1,"unit":"unidad","calories":15,"protein":1,"carbs":2,"fat":1}]',
 '1. Hervir yuca hasta blanda, machar hasta suave. 2. Sofreír cebolla y tomate. 3. Agregar mantequilla de maní y caldo. 4. Cocinar pollo en sopa 20 min. 5. Servir sopa sobre fufu.',
 994, 100, 65, 36, 6, 820,
 '["dinner","carb-loading","west-african","high-protein"]', '["runners","cyclists"]',
 'https://images.pexels.com/photos/3026804/pexels-photo-3026804.jpeg', true),

-- INDIAN - MORE
(NULL, 'Khichdi de recuperación / Recovery Khichdi', 'Khichdi de recuperación', 'Recovery Khichdi', 'indian',
 'Gachas reconfortantes de arroz y lentejas indias, fáciles de digerir | Comforting Indian rice and lentil porridge, easy to digest',
 'recovery', 5, 25, 1,
 '[{"name":"arroz basmati / basmati rice","quantity":80,"unit":"g","calories":104,"protein":2,"carbs":23,"fat":0},{"name":"lentejas amarillas / yellow lentils","quantity":60,"unit":"g","calories":70,"protein":6,"carbs":12,"fat":0},{"name":"ghee","quantity":10,"unit":"g","calories":90,"protein":0,"carbs":0,"fat":10},{"name":"comino / cumin","quantity":3,"unit":"g","calories":8,"protein":0,"carbs":1,"fat":0},{"name":"cúrcuma / turmeric","quantity":3,"unit":"g","calories":10,"protein":0,"carbs":2,"fat":0},{"name":"jengibre / ginger","quantity":5,"unit":"g","calories":4,"protein":0,"carbs":1,"fat":0}]',
 '1. Lavar arroz y lentejas juntos. 2. Cocinar en 3x agua con cúrcuma y sal 20 min. 3. Templar ghee con comino y jengibre. 4. Mezclar tempero con khichdi. 5. Servir suave y caliente.',
 286, 38, 8, 10, 3, 280,
 '["recovery","easy-digest","post-race","gut-friendly","ayurveda"]', '["runners","cyclists","triathletes","swimmers"]',
 'https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg', true),

(NULL, 'Paratha con pollo tikka / Chicken Tikka Paratha', 'Paratha con pollo tikka', 'Chicken Tikka Paratha', 'indian',
 'Pan indio hojaldrado con pollo tikka marinado al horno | Flaky Indian bread with oven-baked tikka marinated chicken',
 'lunch', 20, 25, 1,
 '[{"name":"paratha / roti integral","quantity":100,"unit":"g","calories":300,"protein":8,"carbs":48,"fat":10},{"name":"pollo / chicken","quantity":150,"unit":"g","calories":247,"protein":46,"carbs":0,"fat":5},{"name":"yogur / yogurt","quantity":60,"unit":"g","calories":58,"protein":9,"carbs":3,"fat":1},{"name":"garam masala","quantity":5,"unit":"g","calories":16,"protein":1,"carbs":3,"fat":1},{"name":"páprika / paprika","quantity":5,"unit":"g","calories":16,"protein":1,"carbs":3,"fat":1},{"name":"ajo y jengibre / garlic and ginger","quantity":15,"unit":"g","calories":18,"protein":1,"carbs":4,"fat":0}]',
 '1. Marinar pollo con yogur, garam masala, páprika, ajo y jengibre 1h. 2. Hornear o asar pollo. 3. Calentar paratha. 4. Servir pollo sobre paratha con chutney de menta.',
 655, 54, 65, 17, 4, 580,
 '["lunch","high-protein","indian","pre-race"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/2233729/pexels-photo-2233729.jpeg', true),

-- LATIN AMERICAN - MORE
(NULL, 'Chicha morada peruana / Peruvian Purple Corn Drink', 'Chicha morada peruana', 'Peruvian Purple Corn Drink', 'latin_american',
 'Bebida energizante de maíz morado con canela y clavo, rica en antioxidantes | Energizing purple corn drink with cinnamon and clove, rich in antioxidants',
 'snack', 10, 40, 4,
 '[{"name":"maíz morado / purple corn","quantity":200,"unit":"g","calories":200,"protein":5,"carbs":44,"fat":1},{"name":"piña / pineapple","quantity":100,"unit":"g","calories":50,"protein":1,"carbs":13,"fat":0},{"name":"manzana / apple","quantity":80,"unit":"g","calories":42,"protein":0,"carbs":11,"fat":0},{"name":"canela / cinnamon","quantity":5,"unit":"g","calories":13,"protein":0,"carbs":3,"fat":0},{"name":"clavo / cloves","quantity":3,"unit":"g","calories":6,"protein":0,"carbs":1,"fat":0},{"name":"azúcar / sugar","quantity":50,"unit":"g","calories":194,"protein":0,"carbs":50,"fat":0}]',
 '1. Hervir maíz morado con canela, clavo y piel de piña 40 min. 2. Colar. 3. Agregar jugo de piña, manzana picada y azúcar. 4. Servir frío con hielo.',
 505, 122, 6, 1, 4, 20,
 '["snack","antioxidants","pre-race","hydration","peruvian"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/1633578/pexels-photo-1633578.jpeg', true),

(NULL, 'Mondongo colombiano / Colombian Mondongo', 'Mondongo colombiano', 'Colombian Tripe Soup', 'latin_american',
 'Sopa colombiana de mondongo con verduras, alta en colágeno y proteína | Colombian tripe soup with vegetables, high in collagen and protein',
 'lunch', 20, 90, 2,
 '[{"name":"mondongo / tripe","quantity":200,"unit":"g","calories":180,"protein":26,"carbs":0,"fat":8},{"name":"papa / potato","quantity":150,"unit":"g","calories":116,"protein":3,"carbs":26,"fat":0},{"name":"zanahoria / carrot","quantity":80,"unit":"g","calories":33,"protein":1,"carbs":8,"fat":0},{"name":"plátano verde / green plantain","quantity":80,"unit":"g","calories":90,"protein":1,"carbs":24,"fat":0},{"name":"arveja / pea","quantity":60,"unit":"g","calories":50,"protein":4,"carbs":9,"fat":0},{"name":"cilantro / cilantro","quantity":10,"unit":"g","calories":2,"protein":0,"carbs":0,"fat":0}]',
 '1. Lavar y cortar mondongo. 2. Cocinar en agua con ajo 1h. 3. Agregar papa, zanahoria, plátano y arvejas. 4. Cocinar 30 min más. 5. Condimentar y servir con cilantro.',
 471, 67, 35, 8, 8, 680,
 '["lunch","high-protein","collagen","traditional","latin-american"]', '["runners","cyclists"]',
 'https://images.pexels.com/photos/5409010/pexels-photo-5409010.jpeg', true),

(NULL, 'Sancocho colombiano / Colombian Sancocho', 'Sancocho colombiano de pollo', 'Colombian Chicken Sancocho', 'latin_american',
 'Sopa reconfortante de pollo, papa, plátano y yuca, clásica colombiana | Comforting chicken soup with potato, plantain and cassava, Colombian classic',
 'dinner', 20, 60, 3,
 '[{"name":"pollo / chicken","quantity":300,"unit":"g","calories":495,"protein":92,"carbs":0,"fat":11},{"name":"papa criolla / yellow potato","quantity":200,"unit":"g","calories":154,"protein":4,"carbs":35,"fat":0},{"name":"plátano / plantain","quantity":150,"unit":"g","calories":168,"protein":2,"carbs":44,"fat":0},{"name":"yuca / cassava","quantity":150,"unit":"g","calories":165,"protein":1,"carbs":39,"fat":0},{"name":"mazorca / corn cob","quantity":100,"unit":"g","calories":86,"protein":3,"carbs":19,"fat":1},{"name":"cilantro / cilantro","quantity":15,"unit":"g","calories":4,"protein":0,"carbs":1,"fat":0}]',
 '1. Hervir pollo con ajo, cebolla y sal. 2. Agregar yuca y plátano troceados. 3. A los 20 min agregar papa y mazorca. 4. Cocinar 30 min más. 5. Servir en bowl grande con cilantro.',
 1072, 138, 102, 12, 10, 680,
 '["dinner","recovery","high-protein","carb-loading","colombian"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/2664216/pexels-photo-2664216.jpeg', true),

-- MEXICAN
(NULL, 'Tlayuda oaxaqueña deportiva / Athlete Oaxacan Tlayuda', 'Tlayuda oaxaqueña deportiva', 'Athlete Oaxacan Tlayuda', 'latin_american',
 'Tortilla tostada grande con frijoles, quesillo y tasajo, alta en proteína | Large toasted tortilla with beans, quesillo and tasajo, high protein',
 'lunch', 10, 15, 1,
 '[{"name":"tortilla grande tostada / large toasted tortilla","quantity":120,"unit":"g","calories":360,"protein":9,"carbs":72,"fat":4},{"name":"frijoles negros / black beans","quantity":100,"unit":"g","calories":133,"protein":9,"carbs":24,"fat":1},{"name":"quesillo / Oaxacan string cheese","quantity":60,"unit":"g","calories":174,"protein":12,"carbs":0,"fat":14},{"name":"tasajo / dried beef","quantity":80,"unit":"g","calories":200,"protein":28,"carbs":0,"fat":10},{"name":"lechuga / lettuce","quantity":30,"unit":"g","calories":5,"protein":0,"carbs":1,"fat":0},{"name":"salsa verde / green salsa","quantity":30,"unit":"ml","calories":10,"protein":0,"carbs":2,"fat":0}]',
 '1. Tostar tortilla grande en comal seco. 2. Untar frijoles negros. 3. Colocar quesillo desmenuzado. 4. Tostar tasajo y colocar encima. 5. Agregar lechuga y salsa verde.',
 882, 99, 58, 29, 9, 820,
 '["lunch","high-protein","mexican","carb-rich"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/1640773/pexels-photo-1640773.jpeg', true),

(NULL, 'Pozole rojo de pollo / Red Chicken Pozole', 'Pozole rojo de pollo', 'Red Chicken Pozole', 'latin_american',
 'Sopa mexicana de maíz cacahuazintle y pollo en caldo rojo picante | Mexican hominy and chicken soup in spicy red broth',
 'dinner', 20, 60, 3,
 '[{"name":"maíz pozolero / hominy corn","quantity":200,"unit":"g","calories":334,"protein":9,"carbs":70,"fat":4},{"name":"pollo / chicken","quantity":300,"unit":"g","calories":495,"protein":92,"carbs":0,"fat":11},{"name":"chile guajillo","quantity":30,"unit":"g","calories":90,"protein":3,"carbs":18,"fat":2},{"name":"ajo / garlic","quantity":20,"unit":"g","calories":27,"protein":1,"carbs":6,"fat":0},{"name":"orégano / oregano","quantity":3,"unit":"g","calories":8,"protein":0,"carbs":2,"fat":0},{"name":"tostadas / tostadas","quantity":40,"unit":"g","calories":184,"protein":4,"carbs":36,"fat":4}]',
 '1. Tostar y remojar chiles, licuar con ajo. 2. Cocer pollo y desmenuzar. 3. Agregar maíz pozolero al caldo. 4. Añadir salsa de chile y cocinar 30 min. 5. Servir con tostadas, orégano y rábanos.',
 1138, 131, 109, 21, 14, 820,
 '["dinner","recovery","high-protein","carb-loading","mexican"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/5409010/pexels-photo-5409010.jpeg', true),

-- RACE-DAY SPECIFIC
(NULL, 'Mochi de arroz energético / Energy Rice Mochi', 'Mochi de arroz energético', 'Energy Rice Mochi', 'japanese',
 'Pasteles japoneses de arroz pegajoso, snack de carrera portátil | Japanese sticky rice cakes, portable race day snack',
 'during_race', 10, 20, 4,
 '[{"name":"arroz mochiko / sweet rice flour","quantity":200,"unit":"g","calories":720,"protein":12,"carbs":160,"fat":2},{"name":"azúcar / sugar","quantity":40,"unit":"g","calories":155,"protein":0,"carbs":40,"fat":0},{"name":"agua / water","quantity":180,"unit":"ml","calories":0,"protein":0,"carbs":0,"fat":0},{"name":"frijoles rojos an / red bean paste","quantity":80,"unit":"g","calories":188,"protein":5,"carbs":42,"fat":0}]',
 '1. Mezclar harina con azúcar y agua hasta pasta suave. 2. Cocinar al vapor 15 min. 3. Estirar, rellenar con pasta de frijol. 4. Dar forma esférica. 5. Refrigerar. 6. Llevar en bolsita de carrera.',
 1063, 242, 17, 2, 3, 20,
 '["during_race","portable","energy","quick-carbs","sweet"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/1633578/pexels-photo-1633578.jpeg', true),

(NULL, 'Batido pre-maratón / Pre-Marathon Smoothie', 'Batido pre-maratón de carbohidratos', 'Pre-Marathon Carbohydrate Smoothie', 'global',
 'Batido energético de carbohidratos simples para las 2 horas antes de un maratón | Simple carbohydrate energy smoothie for 2 hours before a marathon',
 'pre_race', 5, 0, 1,
 '[{"name":"plátano maduro / ripe banana","quantity":2,"unit":"mediano","calories":178,"protein":2,"carbs":46,"fat":1},{"name":"jugo de naranja / orange juice","quantity":200,"unit":"ml","calories":86,"protein":1,"carbs":20,"fat":0},{"name":"miel / honey","quantity":15,"unit":"ml","calories":45,"protein":0,"carbs":12,"fat":0},{"name":"leche de avena / oat milk","quantity":100,"unit":"ml","calories":50,"protein":1,"carbs":9,"fat":1},{"name":"copos de avena / rolled oats","quantity":30,"unit":"g","calories":111,"protein":4,"carbs":20,"fat":2}]',
 '1. Colocar todos los ingredientes en licuadora. 2. Licuar hasta suave. 3. Consumir 90-120 min antes de la largada. 4. No agregar proteína (retarda digestión pre-carrera).',
 470, 107, 8, 4, 3, 50,
 '["pre_race","carb-loading","liquid","fast-digest"]', '["runners","cyclists","triathletes","swimmers"]',
 'https://images.pexels.com/photos/1633578/pexels-photo-1633578.jpeg', true),

(NULL, 'Bolitas de energía de triatlón / Triathlon Energy Balls', 'Bolitas de energía de triatlón', 'Triathlon Energy Balls', 'global',
 'Bolitas proteicas de avena, dátil y maní para llevar durante un triatlón | Protein oat, date and peanut balls to carry during a triathlon',
 'during_race', 15, 0, 4,
 '[{"name":"dátiles / dates","quantity":150,"unit":"g","calories":408,"protein":4,"carbs":109,"fat":1},{"name":"avena / rolled oats","quantity":80,"unit":"g","calories":296,"protein":10,"carbs":54,"fat":6},{"name":"mantequilla de maní / peanut butter","quantity":60,"unit":"g","calories":360,"protein":14,"carbs":12,"fat":30},{"name":"cacao en polvo / cocoa powder","quantity":15,"unit":"g","calories":36,"protein":3,"carbs":9,"fat":2},{"name":"semillas de chía / chia seeds","quantity":15,"unit":"g","calories":73,"protein":2,"carbs":6,"fat":5}]',
 '1. Deshuesar dátiles y procesar en procesadora. 2. Agregar avena, maní, cacao y chía. 3. Mezclar hasta masa compacta. 4. Formar bolitas del tamaño de un bocado. 5. Refrigerar 1h. 6. Envolver en papel film para llevar.',
 1173, 190, 33, 44, 16, 80,
 '["during_race","portable","energy","endurance","no-cook"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg', true),

-- GLOBAL ATHLETIC SPECIFICS
(NULL, 'Tostadas de aguacate con salmón / Avocado Salmon Toast', 'Tostadas de aguacate con salmón', 'Avocado Salmon Toast', 'global',
 'Tostadas con aguacate cremoso, salmón y huevo, desayuno completo deportivo | Toast with creamy avocado, salmon and egg, complete sports breakfast',
 'breakfast', 10, 5, 1,
 '[{"name":"pan de masa madre / sourdough bread","quantity":100,"unit":"g","calories":274,"protein":9,"carbs":53,"fat":2},{"name":"aguacate / avocado","quantity":80,"unit":"g","calories":128,"protein":2,"carbs":7,"fat":12},{"name":"salmón ahumado / smoked salmon","quantity":80,"unit":"g","calories":117,"protein":18,"carbs":0,"fat":5},{"name":"huevo pochado / poached egg","quantity":1,"unit":"unidad","calories":78,"protein":6,"carbs":0,"fat":5},{"name":"limón / lemon","quantity":5,"unit":"ml","calories":2,"protein":0,"carbs":1,"fat":0},{"name":"semillas de sésamo / sesame seeds","quantity":5,"unit":"g","calories":28,"protein":1,"carbs":1,"fat":2}]',
 '1. Tostar pan. 2. Prensar aguacate con limón y sal. 3. Untar sobre tostada. 4. Colocar salmón encima. 5. Pochar huevo y colocar sobre salmón. 6. Espolvorear sésamo.',
 627, 62, 36, 26, 7, 760,
 '["breakfast","omega3","high-protein","pre-race"]', '["runners","cyclists","triathletes","swimmers"]',
 'https://images.pexels.com/photos/1640771/pexels-photo-1640771.jpeg', true),

(NULL, 'Bowl de atún y arroz / Tuna Rice Bowl', 'Bowl de atún y arroz integral', 'Brown Rice Tuna Bowl', 'global',
 'Bowl proteico de arroz integral con atún, aguacate y edamame | Protein brown rice bowl with tuna, avocado and edamame',
 'lunch', 10, 20, 1,
 '[{"name":"arroz integral / brown rice","quantity":180,"unit":"g","calories":216,"protein":5,"carbs":45,"fat":2},{"name":"atún en agua / tuna in water","quantity":120,"unit":"g","calories":139,"protein":30,"carbs":0,"fat":1},{"name":"aguacate / avocado","quantity":60,"unit":"g","calories":96,"protein":1,"carbs":5,"fat":9},{"name":"edamame","quantity":80,"unit":"g","calories":94,"protein":8,"carbs":7,"fat":4},{"name":"pepino / cucumber","quantity":50,"unit":"g","calories":7,"protein":0,"carbs":1,"fat":0},{"name":"salsa de soja / soy sauce","quantity":10,"unit":"ml","calories":6,"protein":1,"carbs":1,"fat":0},{"name":"sésamo / sesame","quantity":5,"unit":"g","calories":28,"protein":1,"carbs":1,"fat":2}]',
 '1. Cocinar arroz integral. 2. Escurrir atún y mezclar con soja. 3. Pelar y laminar aguacate. 4. Servir arroz en bowl. 5. Colocar atún, aguacate, edamame y pepino. 6. Espolvorear sésamo.',
 586, 60, 45, 18, 8, 680,
 '["lunch","high-protein","omega3","balanced"]', '["runners","cyclists","triathletes","swimmers"]',
 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg', true),

(NULL, 'Waffles de avena proteicos / Protein Oat Waffles', 'Waffles de avena proteicos', 'Protein Oat Waffles', 'global',
 'Waffles de avena con proteína de vainilla, frutas y miel | Oat waffles with vanilla protein, fruits and honey',
 'breakfast', 10, 15, 2,
 '[{"name":"avena en polvo / oat flour","quantity":80,"unit":"g","calories":296,"protein":10,"carbs":54,"fat":6},{"name":"proteína de vainilla / vanilla protein powder","quantity":30,"unit":"g","calories":120,"protein":24,"carbs":3,"fat":2},{"name":"huevo / egg","quantity":2,"unit":"unidad","calories":155,"protein":13,"carbs":1,"fat":11},{"name":"leche / milk","quantity":100,"unit":"ml","calories":61,"protein":3,"carbs":5,"fat":3},{"name":"frutas del bosque / berries","quantity":80,"unit":"g","calories":40,"protein":1,"carbs":10,"fat":0},{"name":"miel / honey","quantity":15,"unit":"ml","calories":45,"protein":0,"carbs":12,"fat":0}]',
 '1. Mezclar avena, proteína, huevos y leche hasta masa homogénea. 2. Precalentar waflera. 3. Cocinar waffles 4-5 min cada uno. 4. Servir con frutas y miel.',
 717, 85, 51, 22, 7, 180,
 '["breakfast","high-protein","pre-race","sweet"]', '["runners","cyclists","triathletes","swimmers"]',
 'https://images.pexels.com/photos/1640771/pexels-photo-1640771.jpeg', true),

(NULL, 'Ensalada de garbanzos mediterránea / Mediterranean Chickpea Salad', 'Ensalada de garbanzos mediterránea', 'Mediterranean Chickpea Salad', 'mediterranean',
 'Ensalada fresca de garbanzos con tomate, pepino, feta y hierbas mediterráneas | Fresh chickpea salad with tomato, cucumber, feta and Mediterranean herbs',
 'lunch', 10, 0, 1,
 '[{"name":"garbanzos cocidos / cooked chickpeas","quantity":150,"unit":"g","calories":246,"protein":13,"carbs":41,"fat":4},{"name":"tomate cherry / cherry tomato","quantity":100,"unit":"g","calories":18,"protein":1,"carbs":4,"fat":0},{"name":"pepino / cucumber","quantity":80,"unit":"g","calories":11,"protein":1,"carbs":2,"fat":0},{"name":"queso feta / feta cheese","quantity":40,"unit":"g","calories":106,"protein":6,"carbs":2,"fat":9},{"name":"olivas / olives","quantity":30,"unit":"g","calories":36,"protein":0,"carbs":2,"fat":3},{"name":"aceite de oliva / olive oil","quantity":15,"unit":"ml","calories":133,"protein":0,"carbs":0,"fat":15},{"name":"limón / lemon","quantity":15,"unit":"ml","calories":4,"protein":0,"carbs":1,"fat":0}]',
 '1. Escurrir y enjuagar garbanzos. 2. Cortar tomate, pepino y feta. 3. Mezclar todo. 4. Aderezar con aceite, limón, orégano y sal. 5. Servir frío.',
 554, 52, 21, 31, 11, 680,
 '["lunch","plant-based","no-cook","mediterranean","high-fiber"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/1640772/pexels-photo-1640772.jpeg', true),

(NULL, 'Pollo al limón con batata / Lemon Chicken with Sweet Potato', 'Pollo al limón con batata asada', 'Lemon Chicken with Roasted Sweet Potato', 'global',
 'Pechuga de pollo al limón y hierbas con batata asada y brócoli | Lemon herb chicken breast with roasted sweet potato and broccoli',
 'dinner', 15, 35, 1,
 '[{"name":"pechuga de pollo / chicken breast","quantity":180,"unit":"g","calories":297,"protein":56,"carbs":0,"fat":7},{"name":"batata / sweet potato","quantity":200,"unit":"g","calories":172,"protein":4,"carbs":40,"fat":0},{"name":"brócoli / broccoli","quantity":150,"unit":"g","calories":51,"protein":4,"carbs":10,"fat":1},{"name":"aceite de oliva / olive oil","quantity":10,"unit":"ml","calories":88,"protein":0,"carbs":0,"fat":10},{"name":"limón / lemon","quantity":1,"unit":"unidad","calories":20,"protein":0,"carbs":7,"fat":0},{"name":"romero / rosemary","quantity":3,"unit":"g","calories":4,"protein":0,"carbs":1,"fat":0}]',
 '1. Marinar pollo con limón, aceite, romero y sal 30 min. 2. Cortar batata en cubos y condimentar con aceite. 3. Hornear batata 20 min a 200°C. 4. Agregar pollo y brócoli, hornear 20 min más. 5. Servir todo junto.',
 632, 58, 64, 18, 9, 360,
 '["dinner","high-protein","low-fat","balanced","pre-race"]', '["runners","cyclists","triathletes","swimmers"]',
 'https://images.pexels.com/photos/2664216/pexels-photo-2664216.jpeg', true),

(NULL, 'Crema de espinaca y lentejas / Spinach Lentil Cream', 'Crema de espinaca y lentejas rojas', 'Spinach Red Lentil Cream', 'global',
 'Sopa cremosa de espinaca y lentejas rojas, alta en hierro | Creamy spinach and red lentil soup, high in iron',
 'lunch', 10, 25, 2,
 '[{"name":"lentejas rojas / red lentils","quantity":120,"unit":"g","calories":139,"protein":10,"carbs":24,"fat":0},{"name":"espinaca / spinach","quantity":150,"unit":"g","calories":35,"protein":4,"carbs":6,"fat":0},{"name":"caldo de verduras / vegetable broth","quantity":600,"unit":"ml","calories":24,"protein":2,"carbs":4,"fat":0},{"name":"cebolla / onion","quantity":80,"unit":"g","calories":32,"protein":1,"carbs":7,"fat":0},{"name":"ajo / garlic","quantity":10,"unit":"g","calories":13,"protein":1,"carbs":3,"fat":0},{"name":"cúrcuma / turmeric","quantity":5,"unit":"g","calories":16,"protein":0,"carbs":3,"fat":0},{"name":"aceite de coco / coconut oil","quantity":10,"unit":"ml","calories":88,"protein":0,"carbs":0,"fat":10}]',
 '1. Sofreír cebolla y ajo en aceite. 2. Agregar lentejas y cúrcuma. 3. Verter caldo y cocinar 20 min. 4. Agregar espinaca últimos 5 min. 5. Licuar hasta crema suave. 6. Servir con pan integral.',
 347, 47, 18, 10, 11, 480,
 '["lunch","iron-rich","plant-based","high-fiber","vegan"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/3297948/pexels-photo-3297948.jpeg', true);
