/*
  # Seed Athlete Recipes - Batch 4 Final (Fixed)

  Adds final system recipes to complete the 150-recipe collection.
  All JSON fields validated - no invalid characters.
*/

INSERT INTO recipes (
  user_id, name, name_es, name_en, culture, description, category,
  prep_time_min, cook_time_min, servings,
  ingredients, instructions,
  calories_kcal, carbs_g, protein_g, fat_g, fiber_g, sodium_mg,
  tags, suitable_for, image_url, is_public
) VALUES

(NULL, 'Batido de recuperación de nadador / Swimmer Recovery Shake', 'Batido de recuperación de nadador', 'Swimmer Recovery Shake', 'global',
 'Batido de recuperación post-natación con proteína, carbohidratos y electrolitos | Post-swim recovery shake with protein, carbohydrates and electrolytes',
 'post_race', 5, 0, 1,
 '[{"name":"proteína de suero / whey protein","quantity":30,"unit":"g","calories":120,"protein":24,"carbs":3,"fat":2},{"name":"leche / milk","quantity":300,"unit":"ml","calories":183,"protein":9,"carbs":14,"fat":8},{"name":"plátano / banana","quantity":1,"unit":"mediano","calories":89,"protein":1,"carbs":23,"fat":0},{"name":"mantequilla de almendras / almond butter","quantity":20,"unit":"g","calories":120,"protein":4,"carbs":3,"fat":11},{"name":"miel / honey","quantity":10,"unit":"ml","calories":30,"protein":0,"carbs":8,"fat":0}]',
 '1. Colocar todos los ingredientes en licuadora. 2. Licuar 30 segundos. 3. Consumir dentro de los 30 min post-entrenamiento.',
 542, 51, 38, 21, 2, 220,
 '["post_race","recovery","swimmers","high-protein","quick"]', '["swimmers","triathletes"]',
 'https://images.pexels.com/photos/1633578/pexels-photo-1633578.jpeg', true),

(NULL, 'Pasta de nadador pre-competencia / Pre-Competition Swimmer Pasta', 'Pasta de nadador pre-competencia', 'Pre-Competition Swimmer Pasta', 'global',
 'Pasta con pollo y salsa ligera de tomate para la noche antes de una competencia | Pasta with chicken and light tomato sauce for the night before a competition',
 'pre_race', 10, 20, 1,
 '[{"name":"pasta integral / whole grain pasta","quantity":120,"unit":"g","calories":432,"protein":16,"carbs":86,"fat":2},{"name":"pechuga de pollo / chicken breast","quantity":120,"unit":"g","calories":198,"protein":37,"carbs":0,"fat":4},{"name":"tomate triturado / crushed tomato","quantity":150,"unit":"g","calories":30,"protein":2,"carbs":6,"fat":0},{"name":"ajo / garlic","quantity":10,"unit":"g","calories":13,"protein":1,"carbs":3,"fat":0},{"name":"aceite de oliva / olive oil","quantity":10,"unit":"ml","calories":88,"protein":0,"carbs":0,"fat":10},{"name":"albahaca / basil","quantity":5,"unit":"g","calories":1,"protein":0,"carbs":0,"fat":0}]',
 '1. Cocer pasta al dente. 2. Sofreír ajo en aceite 1 min. 3. Agregar tomate y cocinar 10 min. 4. Añadir pollo cocido desmenuzado. 5. Mezclar pasta con salsa y servir.',
 762, 95, 56, 16, 7, 380,
 '["pre_race","carb-loading","swimmers","high-protein"]', '["swimmers","triathletes","runners"]',
 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg', true),

(NULL, 'Pastel de arroz para ciclismo / Cycling Rice Cake', 'Pastel de arroz para ciclismo', 'Cycling Rice Cake', 'global',
 'Pastel de arroz con pollo y salsa de soja, snack clásico de ciclismo | Rice cake with chicken and soy sauce, classic cycling snack',
 'during_race', 15, 20, 4,
 '[{"name":"arroz de grano corto / short grain rice","quantity":200,"unit":"g","calories":260,"protein":5,"carbs":57,"fat":0},{"name":"pollo desmenuzado / shredded chicken","quantity":80,"unit":"g","calories":132,"protein":25,"carbs":0,"fat":3},{"name":"salsa de soja / soy sauce","quantity":20,"unit":"ml","calories":12,"protein":2,"carbs":2,"fat":0},{"name":"aceite de sésamo / sesame oil","quantity":5,"unit":"ml","calories":45,"protein":0,"carbs":0,"fat":5},{"name":"cebollita / green onion","quantity":10,"unit":"g","calories":3,"protein":0,"carbs":1,"fat":0}]',
 '1. Cocer arroz de grano corto (queda pegajoso). 2. Mezclar con pollo, soja y aceite de sésamo. 3. Aplastar en bandeja cubierta con film. 4. Refrigerar 1h. 5. Cortar en rectángulos. 6. Envolver cada uno en papel film.',
 452, 60, 32, 8, 1, 420,
 '["during_race","portable","cyclists","energy","no-bake"]', '["cyclists","triathletes"]',
 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg', true),

(NULL, 'Bowl de recuperación ciclista / Cyclist Recovery Bowl', 'Bowl de recuperación ciclista', 'Cyclist Recovery Bowl', 'global',
 'Bowl de recuperación 4:1 (carb:proteína) para ciclistas | 4:1 ratio recovery bowl for cyclists',
 'recovery', 10, 25, 1,
 '[{"name":"arroz blanco / white rice","quantity":200,"unit":"g","calories":260,"protein":5,"carbs":57,"fat":0},{"name":"pechuga de pollo / chicken breast","quantity":100,"unit":"g","calories":165,"protein":31,"carbs":0,"fat":4},{"name":"brócoli / broccoli","quantity":100,"unit":"g","calories":34,"protein":3,"carbs":7,"fat":0},{"name":"zanahoria / carrot","quantity":60,"unit":"g","calories":25,"protein":1,"carbs":6,"fat":0},{"name":"salsa teriyaki / teriyaki sauce","quantity":25,"unit":"ml","calories":55,"protein":1,"carbs":13,"fat":0},{"name":"semillas de sésamo / sesame seeds","quantity":5,"unit":"g","calories":28,"protein":1,"carbs":1,"fat":2}]',
 '1. Cocer arroz. 2. Asar pollo con teriyaki. 3. Cocinar brócoli y zanahoria al vapor. 4. Armar bowl con arroz base, pollo y verduras. 5. Bañar con teriyaki y espolvorear sésamo.',
 567, 84, 41, 6, 5, 680,
 '["recovery","post_race","cyclists","4-1-ratio","high-carb"]', '["cyclists","triathletes","runners"]',
 'https://images.pexels.com/photos/2664216/pexels-photo-2664216.jpeg', true),

(NULL, 'Papas de media maratón / Half Marathon Potatoes', 'Papas de media maratón', 'Half Marathon Boiled Potatoes', 'global',
 'Papas hervidas con sal marina, snack simple y efectivo para ultra trail | Boiled potatoes with sea salt, simple and effective ultra trail snack',
 'during_race', 5, 20, 2,
 '[{"name":"papas pequeñas / small potatoes","quantity":300,"unit":"g","calories":231,"protein":6,"carbs":51,"fat":0},{"name":"sal marina gruesa / coarse sea salt","quantity":3,"unit":"g","calories":0,"protein":0,"carbs":0,"fat":0},{"name":"aceite de oliva / olive oil","quantity":5,"unit":"ml","calories":44,"protein":0,"carbs":0,"fat":5}]',
 '1. Hervir papas con sal hasta blandas. 2. Enfriar. 3. Rociar con aceite y sal gruesa. 4. Colocar en bolsa zip para llevar. 5. Consumir durante trail cada 45-60 min.',
 275, 51, 6, 5, 4, 580,
 '["during_race","trail","ultra","portable","real-food"]', '["runners","trail-runners"]',
 'https://images.pexels.com/photos/5835353/pexels-photo-5835353.jpeg', true),

(NULL, 'Caldo de huesos de corredor / Runner Bone Broth', 'Caldo de huesos de corredor', 'Runner Bone Broth', 'global',
 'Caldo de huesos rico en colágeno y electrolitos para recuperación articular | Bone broth rich in collagen and electrolytes for joint recovery',
 'recovery', 10, 180, 4,
 '[{"name":"huesos de res / beef bones","quantity":500,"unit":"g","calories":200,"protein":20,"carbs":0,"fat":12},{"name":"cebolla / onion","quantity":100,"unit":"g","calories":40,"protein":1,"carbs":9,"fat":0},{"name":"zanahoria / carrot","quantity":100,"unit":"g","calories":41,"protein":1,"carbs":10,"fat":0},{"name":"apio / celery","quantity":60,"unit":"g","calories":10,"protein":0,"carbs":2,"fat":0},{"name":"vinagre de manzana / apple cider vinegar","quantity":30,"unit":"ml","calories":6,"protein":0,"carbs":1,"fat":0},{"name":"ajo / garlic","quantity":20,"unit":"g","calories":27,"protein":1,"carbs":6,"fat":0}]',
 '1. Tostar huesos 30 min a 200°C. 2. Colocar en olla con agua, verduras y vinagre. 3. Hervir y luego cocinar a fuego muy bajo 4-8h. 4. Colar. 5. Consumir caliente o enfriar y refrigerar.',
 324, 28, 23, 12, 3, 680,
 '["recovery","collagen","joints","anti-inflammatory","long-cook"]', '["runners","trail-runners","triathletes"]',
 'https://images.pexels.com/photos/3297948/pexels-photo-3297948.jpeg', true),

(NULL, 'Risotto de remolacha y cabra / Beet Goat Cheese Risotto', 'Risotto de remolacha y queso de cabra', 'Beet and Goat Cheese Risotto', 'italian',
 'Risotto cremoso de remolacha con queso de cabra, alto en nitratos | Creamy beet risotto with goat cheese, high in nitrates',
 'dinner', 10, 30, 2,
 '[{"name":"arroz arborio / arborio rice","quantity":160,"unit":"g","calories":571,"protein":12,"carbs":124,"fat":2},{"name":"remolacha cocida / cooked beet","quantity":150,"unit":"g","calories":64,"protein":2,"carbs":15,"fat":0},{"name":"queso de cabra / goat cheese","quantity":60,"unit":"g","calories":159,"protein":11,"carbs":0,"fat":13},{"name":"caldo de verduras / vegetable broth","quantity":600,"unit":"ml","calories":24,"protein":2,"carbs":4,"fat":0},{"name":"vino blanco / white wine","quantity":60,"unit":"ml","calories":46,"protein":0,"carbs":4,"fat":0},{"name":"cebolla / onion","quantity":60,"unit":"g","calories":24,"protein":1,"carbs":6,"fat":0},{"name":"aceite de oliva / olive oil","quantity":10,"unit":"ml","calories":88,"protein":0,"carbs":0,"fat":10}]',
 '1. Sofreír cebolla en aceite. 2. Agregar arroz y tostar 2 min. 3. Añadir vino y absorber. 4. Agregar caldo caliente poco a poco revolviendo 20 min. 5. Incorporar remolacha rallada. 6. Servir con queso de cabra.',
 976, 149, 28, 25, 4, 580,
 '["dinner","pre-race","carb-loading","nitrates","italian"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg', true),

(NULL, 'Panzanella toscana / Tuscan Panzanella', 'Panzanella toscana', 'Tuscan Panzanella', 'italian',
 'Ensalada toscana de pan con tomate, aceitunas y albahaca | Tuscan bread salad with tomato, olives and basil',
 'lunch', 15, 0, 1,
 '[{"name":"pan de campo duro / stale country bread","quantity":100,"unit":"g","calories":265,"protein":9,"carbs":52,"fat":2},{"name":"tomate maduro / ripe tomato","quantity":200,"unit":"g","calories":36,"protein":2,"carbs":8,"fat":0},{"name":"pepino / cucumber","quantity":80,"unit":"g","calories":11,"protein":1,"carbs":2,"fat":0},{"name":"cebolla roja / red onion","quantity":40,"unit":"g","calories":16,"protein":0,"carbs":4,"fat":0},{"name":"albahaca fresca / fresh basil","quantity":10,"unit":"g","calories":3,"protein":0,"carbs":0,"fat":0},{"name":"aceitunas / olives","quantity":30,"unit":"g","calories":36,"protein":0,"carbs":2,"fat":3},{"name":"aceite de oliva / olive oil","quantity":20,"unit":"ml","calories":177,"protein":0,"carbs":0,"fat":20},{"name":"vinagre / vinegar","quantity":10,"unit":"ml","calories":2,"protein":0,"carbs":0,"fat":0}]',
 '1. Remojar pan en agua fría 10 min, exprimir. 2. Cortar tomate, pepino y cebolla. 3. Mezclar todo con aceitunas. 4. Aderezar con aceite y vinagre. 5. Agregar albahaca fresca. 6. Reposar 15 min.',
 546, 66, 12, 25, 5, 580,
 '["lunch","mediterranean","italian","no-cook","summer"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/1640772/pexels-photo-1640772.jpeg', true),

(NULL, 'Gazpacho andaluz / Andalusian Gazpacho', 'Gazpacho andaluz', 'Andalusian Gazpacho', 'spanish',
 'Sopa fría española de tomate y verduras, hidratante y antioxidante | Spanish cold tomato and vegetable soup, hydrating and antioxidant',
 'snack', 15, 0, 2,
 '[{"name":"tomate maduro / ripe tomato","quantity":400,"unit":"g","calories":72,"protein":4,"carbs":16,"fat":0},{"name":"pimiento verde / green pepper","quantity":80,"unit":"g","calories":18,"protein":1,"carbs":4,"fat":0},{"name":"pepino / cucumber","quantity":100,"unit":"g","calories":14,"protein":1,"carbs":3,"fat":0},{"name":"ajo / garlic","quantity":10,"unit":"g","calories":13,"protein":1,"carbs":3,"fat":0},{"name":"pan de ayer / stale bread","quantity":40,"unit":"g","calories":106,"protein":3,"carbs":21,"fat":1},{"name":"aceite de oliva / olive oil","quantity":20,"unit":"ml","calories":177,"protein":0,"carbs":0,"fat":20},{"name":"vinagre de jerez / sherry vinegar","quantity":15,"unit":"ml","calories":4,"protein":0,"carbs":1,"fat":0}]',
 '1. Remojar pan en agua. 2. Licuar tomates, pimiento, pepino y ajo. 3. Agregar pan remojado y aceite. 4. Condimentar con vinagre y sal. 5. Colar para suavidad. 6. Refrigerar 2h antes de servir.',
 404, 48, 10, 21, 6, 480,
 '["snack","pre-workout","hydration","antioxidants","summer","vegan"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/3297948/pexels-photo-3297948.jpeg', true),

(NULL, 'Ensalada griega clásica / Classic Greek Salad', 'Ensalada griega clásica', 'Classic Greek Salad', 'mediterranean',
 'Horiatiki clásica con tomate, pepino, feta, olivas y orégano | Classic horiatiki with tomato, cucumber, feta, olives and oregano',
 'lunch', 10, 0, 1,
 '[{"name":"tomate / tomato","quantity":200,"unit":"g","calories":36,"protein":2,"carbs":8,"fat":0},{"name":"pepino / cucumber","quantity":120,"unit":"g","calories":16,"protein":1,"carbs":3,"fat":0},{"name":"cebolla roja / red onion","quantity":40,"unit":"g","calories":16,"protein":0,"carbs":4,"fat":0},{"name":"queso feta / feta cheese","quantity":80,"unit":"g","calories":213,"protein":12,"carbs":3,"fat":18},{"name":"aceitunas / olives","quantity":40,"unit":"g","calories":48,"protein":0,"carbs":3,"fat":4},{"name":"aceite de oliva / olive oil","quantity":20,"unit":"ml","calories":177,"protein":0,"carbs":0,"fat":20},{"name":"orégano / oregano","quantity":2,"unit":"g","calories":5,"protein":0,"carbs":1,"fat":0}]',
 '1. Cortar tomate en trozos grandes. 2. Pelar y cortar pepino. 3. Filetear cebolla roja. 4. Agregar aceitunas. 5. Poner bloque de feta encima. 6. Rociar aceite, orégano y sal.',
 511, 22, 15, 42, 5, 820,
 '["lunch","mediterranean","no-cook","greek","light"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/1640772/pexels-photo-1640772.jpeg', true),

(NULL, 'Souvlaki de pollo / Chicken Souvlaki', 'Souvlaki de pollo con pita y tzatziki', 'Chicken Souvlaki with Pita and Tzatziki', 'mediterranean',
 'Brochetas griegas de pollo marinado con pita y tzatziki casero | Greek marinated chicken skewers with pita and homemade tzatziki',
 'dinner', 20, 15, 1,
 '[{"name":"pechuga de pollo / chicken breast","quantity":180,"unit":"g","calories":297,"protein":56,"carbs":0,"fat":7},{"name":"pan pita / pita bread","quantity":80,"unit":"g","calories":220,"protein":7,"carbs":44,"fat":1},{"name":"yogur griego / Greek yogurt","quantity":100,"unit":"g","calories":97,"protein":15,"carbs":5,"fat":1},{"name":"pepino / cucumber","quantity":60,"unit":"g","calories":8,"protein":0,"carbs":2,"fat":0},{"name":"ajo / garlic","quantity":5,"unit":"g","calories":7,"protein":0,"carbs":2,"fat":0},{"name":"limón / lemon","quantity":1,"unit":"unidad","calories":20,"protein":0,"carbs":7,"fat":0},{"name":"orégano y comino","quantity":3,"unit":"g","calories":8,"protein":0,"carbs":2,"fat":0}]',
 '1. Marinar pollo con aceite, limón, ajo y orégano 1h. 2. Ensartar en pinchos y asar 12-15 min. 3. Preparar tzatziki: yogur, pepino rallado, ajo y eneldo. 4. Servir pollo en pita con tzatziki.',
 657, 60, 79, 9, 3, 580,
 '["dinner","high-protein","mediterranean","greek"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/2233729/pexels-photo-2233729.jpeg', true),

(NULL, 'Menemen turco / Turkish Menemen', 'Menemen turco con pan', 'Turkish Menemen with Bread', 'middle_eastern',
 'Huevos turcos revueltos con tomate, pimiento y especias | Turkish scrambled eggs with tomato, pepper and spices',
 'breakfast', 10, 15, 1,
 '[{"name":"huevos / eggs","quantity":3,"unit":"unidad","calories":233,"protein":19,"carbs":1,"fat":16},{"name":"tomate / tomato","quantity":150,"unit":"g","calories":27,"protein":1,"carbs":6,"fat":0},{"name":"pimiento verde / green pepper","quantity":80,"unit":"g","calories":18,"protein":1,"carbs":4,"fat":0},{"name":"aceite de oliva / olive oil","quantity":10,"unit":"ml","calories":88,"protein":0,"carbs":0,"fat":10},{"name":"pimentón / paprika","quantity":5,"unit":"g","calories":16,"protein":1,"carbs":3,"fat":1},{"name":"pan / bread","quantity":60,"unit":"g","calories":160,"protein":5,"carbs":32,"fat":1}]',
 '1. Sofreír pimiento en aceite 3 min. 2. Agregar tomate triturado y pimentón. 3. Cocinar 5 min. 4. Romper huevos encima y revolver suavemente. 5. Cocinar hasta cuajar. 6. Servir con pan.',
 542, 46, 26, 28, 4, 480,
 '["breakfast","high-protein","turkish","eggs","quick"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/4721265/pexels-photo-4721265.jpeg', true),

(NULL, 'Causa limeña de atún / Tuna Causa Limena', 'Causa limeña de atún', 'Tuna Causa Limena', 'latin_american',
 'Causa peruana de papa amarilla con atún, palta y ají amarillo | Peruvian yellow potato causa with tuna, avocado and yellow pepper',
 'lunch', 25, 20, 2,
 '[{"name":"papa amarilla / yellow potato","quantity":300,"unit":"g","calories":231,"protein":6,"carbs":51,"fat":0},{"name":"atún en agua / tuna in water","quantity":120,"unit":"g","calories":139,"protein":30,"carbs":0,"fat":1},{"name":"palta / avocado","quantity":80,"unit":"g","calories":128,"protein":2,"carbs":7,"fat":12},{"name":"ají amarillo pasta","quantity":20,"unit":"g","calories":30,"protein":1,"carbs":5,"fat":1},{"name":"mayonesa light / light mayo","quantity":20,"unit":"g","calories":60,"protein":0,"carbs":1,"fat":6},{"name":"limón / lime","quantity":1,"unit":"unidad","calories":20,"protein":0,"carbs":7,"fat":0}]',
 '1. Hervir papas, aplastar con ají amarillo, limón y aceite. 2. Salpimentar. 3. Mezclar atún con mayonesa. 4. Armar en molde: capa de papa, atún, palta y otra capa de papa. 5. Refrigerar 30 min. 6. Desmoldar y servir.',
 608, 66, 33, 20, 8, 480,
 '["lunch","peruvian","high-protein","gluten-free"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg', true),

(NULL, 'Milanesa napolitana / Neapolitan Milanesa', 'Milanesa napolitana con ensalada', 'Neapolitan Milanesa with Salad', 'latin_american',
 'Milanesa de res con salsa de tomate, jamón y queso, clásico argentino | Beef milanesa with tomato sauce, ham and cheese, Argentine classic',
 'dinner', 15, 15, 1,
 '[{"name":"bife de cuadril / beef top round","quantity":200,"unit":"g","calories":320,"protein":46,"carbs":0,"fat":14},{"name":"pan rallado / breadcrumbs","quantity":50,"unit":"g","calories":197,"protein":7,"carbs":36,"fat":3},{"name":"huevo / egg","quantity":1,"unit":"unidad","calories":78,"protein":6,"carbs":0,"fat":5},{"name":"tomate en salsa / tomato sauce","quantity":60,"unit":"g","calories":20,"protein":1,"carbs":4,"fat":0},{"name":"jamón / ham","quantity":40,"unit":"g","calories":52,"protein":7,"carbs":1,"fat":3},{"name":"queso / cheese","quantity":40,"unit":"g","calories":148,"protein":8,"carbs":1,"fat":13}]',
 '1. Aplanar bife. 2. Pasar por huevo batido y pan rallado. 3. Freír en aceite caliente 3 min por lado. 4. Colocar salsa, jamón y queso encima. 5. Gratinar en horno 5 min. 6. Servir con ensalada.',
 815, 38, 75, 38, 1, 820,
 '["dinner","high-protein","argentinian","traditional"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/2233729/pexels-photo-2233729.jpeg', true),

(NULL, 'Açaí bowl de alto rendimiento / High Performance Açaí Bowl', 'Açaí bowl de alto rendimiento', 'High Performance Açaí Bowl', 'latin_american',
 'Bowl de açaí amazónico con granola, plátano y proteína para deportistas | Amazonian açaí bowl with granola, banana and protein for athletes',
 'breakfast', 5, 0, 1,
 '[{"name":"polpa de açaí / açaí pulp","quantity":150,"unit":"g","calories":165,"protein":2,"carbs":18,"fat":10},{"name":"granola","quantity":50,"unit":"g","calories":224,"protein":6,"carbs":38,"fat":7},{"name":"plátano / banana","quantity":1,"unit":"mediano","calories":89,"protein":1,"carbs":23,"fat":0},{"name":"proteína de vainilla / vanilla protein","quantity":20,"unit":"g","calories":80,"protein":16,"carbs":2,"fat":1},{"name":"miel / honey","quantity":10,"unit":"ml","calories":30,"protein":0,"carbs":8,"fat":0},{"name":"frutas del bosque / berries","quantity":60,"unit":"g","calories":30,"protein":1,"carbs":7,"fat":0}]',
 '1. Licuar açaí con proteína y poca leche hasta consistencia espesa. 2. Verter en bowl. 3. Colocar plátano en rodajas, granola y frutas encima. 4. Rociar con miel.',
 618, 96, 26, 18, 7, 80,
 '["breakfast","antioxidants","pre-race","brazilian","amazon"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/1633578/pexels-photo-1633578.jpeg', true),

(NULL, 'Frango com feijão / Chicken with Brazilian Black Beans', 'Frango com feijão brasileiro', 'Chicken with Brazilian Black Beans', 'latin_american',
 'Pollo guisado con feijão preto a la brasileña, clásico del deporte | Brazilian-style chicken stewed with black beans, sports classic',
 'dinner', 15, 40, 2,
 '[{"name":"pollo muslo / chicken thigh","quantity":250,"unit":"g","calories":413,"protein":42,"carbs":0,"fat":28},{"name":"feijão preto / black beans","quantity":200,"unit":"g","calories":266,"protein":18,"carbs":48,"fat":1},{"name":"arroz blanco / white rice","quantity":150,"unit":"g","calories":195,"protein":4,"carbs":43,"fat":0},{"name":"ajo / garlic","quantity":15,"unit":"g","calories":20,"protein":1,"carbs":5,"fat":0},{"name":"cebolla / onion","quantity":80,"unit":"g","calories":32,"protein":1,"carbs":7,"fat":0},{"name":"tomate / tomato","quantity":100,"unit":"g","calories":18,"protein":1,"carbs":4,"fat":0}]',
 '1. Dorar pollo en aceite. 2. Agregar ajo y cebolla. 3. Añadir tomate y guisar 5 min. 4. Incorporar feijão con su caldo. 5. Cocinar 25 min. 6. Servir sobre arroz.',
 944, 107, 66, 29, 12, 620,
 '["dinner","high-protein","carb-loading","brazilian","traditional"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/1640775/pexels-photo-1640775.jpeg', true),

(NULL, 'Quinoto andino / Andean Quinoto', 'Quinoto andino', 'Andean Quinoto', 'latin_american',
 'Risotto de quinoa andina con verduras de temporada, alta proteína completa | Andean quinoa risotto with seasonal vegetables, complete high protein',
 'dinner', 10, 25, 2,
 '[{"name":"quinoa / quinoa","quantity":160,"unit":"g","calories":584,"protein":22,"carbs":105,"fat":10},{"name":"queso de cabra / goat cheese","quantity":50,"unit":"g","calories":133,"protein":9,"carbs":0,"fat":11},{"name":"espinaca / spinach","quantity":100,"unit":"g","calories":23,"protein":3,"carbs":4,"fat":0},{"name":"zanahoria / carrot","quantity":80,"unit":"g","calories":33,"protein":1,"carbs":8,"fat":0},{"name":"caldo de verduras / vegetable broth","quantity":400,"unit":"ml","calories":16,"protein":1,"carbs":3,"fat":0},{"name":"cebolla / onion","quantity":60,"unit":"g","calories":24,"protein":1,"carbs":6,"fat":0}]',
 '1. Sofreír cebolla y zanahoria. 2. Agregar quinoa lavada. 3. Añadir caldo caliente poco a poco como risotto. 4. Incorporar espinaca al final. 5. Servir cremoso con queso de cabra rallado.',
 813, 126, 37, 21, 13, 380,
 '["dinner","complete-protein","andean","vegetarian","high-altitude"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/1640772/pexels-photo-1640772.jpeg', true),

(NULL, 'Tacos de lechuga sin gluten / Gluten-Free Lettuce Tacos', 'Tacos de lechuga sin gluten', 'Gluten-Free Lettuce Tacos', 'global',
 'Tacos de lechuga con pavo, aguacate y salsa fresca, bajo en carbohidratos | Lettuce tacos with turkey, avocado and fresh salsa, low carb',
 'lunch', 15, 10, 1,
 '[{"name":"hojas de lechuga / lettuce leaves","quantity":100,"unit":"g","calories":17,"protein":1,"carbs":3,"fat":0},{"name":"pechuga de pavo / turkey breast","quantity":150,"unit":"g","calories":165,"protein":36,"carbs":0,"fat":1},{"name":"palta / avocado","quantity":80,"unit":"g","calories":128,"protein":2,"carbs":7,"fat":12},{"name":"tomate / tomato","quantity":80,"unit":"g","calories":14,"protein":1,"carbs":3,"fat":0},{"name":"cebolla / onion","quantity":30,"unit":"g","calories":12,"protein":0,"carbs":3,"fat":0},{"name":"cilantro / cilantro","quantity":10,"unit":"g","calories":2,"protein":0,"carbs":0,"fat":0},{"name":"limón / lime","quantity":1,"unit":"unidad","calories":20,"protein":0,"carbs":7,"fat":0}]',
 '1. Cocinar pavo sazonado. 2. Hacer salsa fresca con tomate, cebolla y cilantro. 3. Servir pavo en hojas de lechuga. 4. Coronar con aguacate machacado, salsa y lima.',
 358, 23, 40, 13, 7, 280,
 '["lunch","gluten-free","low-carb","high-protein","keto-friendly"]', '["runners","cyclists","triathletes","swimmers"]',
 'https://images.pexels.com/photos/1640773/pexels-photo-1640773.jpeg', true),

(NULL, 'Batata rellena de brócoli y pollo / Stuffed Sweet Potato', 'Batata rellena de brócoli y pollo', 'Broccoli Chicken Stuffed Sweet Potato', 'global',
 'Batata horneada rellena de pollo y brócoli, sin gluten y nutritiva | Baked sweet potato stuffed with chicken and broccoli, gluten-free and nutritious',
 'dinner', 10, 45, 1,
 '[{"name":"batata grande / large sweet potato","quantity":220,"unit":"g","calories":189,"protein":4,"carbs":44,"fat":0},{"name":"pechuga de pollo / chicken breast","quantity":130,"unit":"g","calories":214,"protein":40,"carbs":0,"fat":5},{"name":"brócoli / broccoli","quantity":100,"unit":"g","calories":34,"protein":3,"carbs":7,"fat":0},{"name":"yogur griego / Greek yogurt","quantity":40,"unit":"g","calories":39,"protein":6,"carbs":2,"fat":1},{"name":"queso rallado / shredded cheese","quantity":30,"unit":"g","calories":111,"protein":7,"carbs":0,"fat":9},{"name":"ajo en polvo / garlic powder","quantity":3,"unit":"g","calories":10,"protein":0,"carbs":2,"fat":0}]',
 '1. Hornear batata 40 min a 200°C. 2. Cocinar pollo con ajo y sazonar. 3. Cocinar brócoli al vapor. 4. Abrir batata, retirar parte de la pulpa. 5. Mezclar pollo, brócoli, yogur y pulpa. 6. Rellenar y gratinar con queso 5 min.',
 587, 53, 60, 15, 9, 420,
 '["dinner","gluten-free","high-protein","balanced","pre-race"]', '["runners","cyclists","triathletes","swimmers"]',
 'https://images.pexels.com/photos/5835353/pexels-photo-5835353.jpeg', true),

(NULL, 'Bowl de tofu y edamame / Tofu Edamame Power Bowl', 'Bowl de poder: tofu y edamame', 'Power Bowl: Tofu and Edamame', 'global',
 'Bowl vegano de arroz, tofu marinado, edamame y verduras salteadas | Vegan rice bowl with marinated tofu, edamame and sautéed vegetables',
 'lunch', 15, 20, 1,
 '[{"name":"arroz integral / brown rice","quantity":180,"unit":"g","calories":216,"protein":5,"carbs":45,"fat":2},{"name":"tofu firme / firm tofu","quantity":150,"unit":"g","calories":117,"protein":13,"carbs":4,"fat":6},{"name":"edamame","quantity":80,"unit":"g","calories":94,"protein":8,"carbs":7,"fat":4},{"name":"brócoli / broccoli","quantity":80,"unit":"g","calories":27,"protein":2,"carbs":6,"fat":0},{"name":"zanahoria / carrot","quantity":50,"unit":"g","calories":21,"protein":0,"carbs":5,"fat":0},{"name":"salsa de soja / soy sauce","quantity":15,"unit":"ml","calories":9,"protein":1,"carbs":1,"fat":0},{"name":"aceite de sésamo / sesame oil","quantity":5,"unit":"ml","calories":45,"protein":0,"carbs":0,"fat":5}]',
 '1. Marinar tofu con soja, ajo y jengibre 30 min. 2. Freír tofu hasta dorado. 3. Saltear brócoli y zanahoria. 4. Cocinar arroz. 5. Armar bowl con todos los componentes. 6. Agregar edamame y sésamo.',
 529, 65, 29, 17, 9, 680,
 '["lunch","vegan","plant-protein","gluten-free","balanced"]', '["runners","cyclists","triathletes","swimmers"]',
 'https://images.pexels.com/photos/2098085/pexels-photo-2098085.jpeg', true),

(NULL, 'Dahl de lentejas del deportista / Athlete Lentil Dahl', 'Dahl de lentejas del deportista', 'Athlete Lentil Dahl', 'indian',
 'Curry indio de lentejas rojas con espinaca y coco, alto en hierro y proteína | Indian red lentil curry with spinach and coconut, high in iron and protein',
 'dinner', 10, 30, 2,
 '[{"name":"lentejas rojas / red lentils","quantity":150,"unit":"g","calories":174,"protein":13,"carbs":30,"fat":0},{"name":"espinaca / spinach","quantity":100,"unit":"g","calories":23,"protein":3,"carbs":4,"fat":0},{"name":"leche de coco / coconut milk","quantity":150,"unit":"ml","calories":173,"protein":2,"carbs":5,"fat":18},{"name":"tomate / tomato","quantity":120,"unit":"g","calories":22,"protein":1,"carbs":5,"fat":0},{"name":"ajo / garlic","quantity":15,"unit":"g","calories":20,"protein":1,"carbs":5,"fat":0},{"name":"garam masala","quantity":5,"unit":"g","calories":16,"protein":1,"carbs":3,"fat":1},{"name":"arroz basmati / basmati rice","quantity":150,"unit":"g","calories":195,"protein":4,"carbs":43,"fat":0}]',
 '1. Sofreír ajo con garam masala. 2. Agregar tomate y cocinar 3 min. 3. Añadir lentejas, agua y leche de coco. 4. Cocinar 20 min. 5. Incorporar espinaca. 6. Servir sobre arroz basmati.',
 623, 85, 24, 19, 11, 380,
 '["dinner","vegan","iron-rich","plant-protein","indian"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg', true),

(NULL, 'Pudín de chía con mango / Mango Chia Pudding', 'Pudín de chía con mango', 'Mango Chia Pudding', 'global',
 'Pudín de chía con mango fresco, rico en omega-3 y fibra | Chia pudding with fresh mango, rich in omega-3 and fiber',
 'snack', 10, 0, 2,
 '[{"name":"semillas de chía / chia seeds","quantity":40,"unit":"g","calories":194,"protein":7,"carbs":16,"fat":12},{"name":"leche de coco / coconut milk","quantity":200,"unit":"ml","calories":230,"protein":2,"carbs":6,"fat":24},{"name":"leche de avena / oat milk","quantity":100,"unit":"ml","calories":50,"protein":1,"carbs":9,"fat":1},{"name":"mango / mango","quantity":150,"unit":"g","calories":90,"protein":1,"carbs":24,"fat":0},{"name":"miel / honey","quantity":10,"unit":"ml","calories":30,"protein":0,"carbs":8,"fat":0},{"name":"vainilla / vanilla","quantity":2,"unit":"ml","calories":5,"protein":0,"carbs":1,"fat":0}]',
 '1. Mezclar chía con leche de coco, oat milk y miel. 2. Refrigerar mínimo 4h o toda la noche. 3. Al servir, cubrir con mango cortado. 4. Decorar con coco rallado.',
 599, 64, 11, 37, 14, 80,
 '["snack","omega3","prep-ahead","vegan","fiber-rich"]', '["runners","cyclists","triathletes","swimmers"]',
 'https://images.pexels.com/photos/1633578/pexels-photo-1633578.jpeg', true),

(NULL, 'Barra energética de dátil y cacao / Date Cocoa Energy Bar', 'Barra energética de dátil y cacao', 'Date Cocoa Energy Bar', 'global',
 'Barras caseras de dátil, coco y cacao sin horno, energía sostenida | Homemade date, coconut and cocoa bars no-bake, sustained energy',
 'snack', 15, 0, 6,
 '[{"name":"dátiles Medjool / Medjool dates","quantity":200,"unit":"g","calories":544,"protein":4,"carbs":145,"fat":1},{"name":"avena / rolled oats","quantity":100,"unit":"g","calories":370,"protein":13,"carbs":67,"fat":7},{"name":"coco rallado / shredded coconut","quantity":40,"unit":"g","calories":142,"protein":1,"carbs":6,"fat":13},{"name":"cacao en polvo / cocoa powder","quantity":20,"unit":"g","calories":48,"protein":4,"carbs":12,"fat":3},{"name":"almendras / almonds","quantity":50,"unit":"g","calories":290,"protein":11,"carbs":10,"fat":25}]',
 '1. Procesar dátiles hasta pasta. 2. Agregar avena, coco, cacao y almendras. 3. Mezclar hasta masa compacta. 4. Presionar en bandeja con papel manteca. 5. Refrigerar 2h. 6. Cortar en barras y envolver.',
 1394, 240, 33, 49, 18, 10,
 '["snack","portable","no-bake","energy","pre-race","vegan"]', '["runners","cyclists","triathletes","swimmers"]',
 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg', true),

(NULL, 'Tazón anti-inflamatorio de cúrcuma / Anti-Inflammatory Turmeric Bowl', 'Tazón anti-inflamatorio de cúrcuma', 'Anti-Inflammatory Turmeric Bowl', 'global',
 'Bowl de arroz con cúrcuma, salmón, aguacate y jengibre para recuperación | Rice bowl with turmeric, salmon, avocado and ginger for recovery',
 'recovery', 10, 20, 1,
 '[{"name":"arroz integral / brown rice","quantity":160,"unit":"g","calories":192,"protein":4,"carbs":40,"fat":2},{"name":"salmón / salmon","quantity":150,"unit":"g","calories":280,"protein":34,"carbs":0,"fat":16},{"name":"aguacate / avocado","quantity":60,"unit":"g","calories":96,"protein":1,"carbs":5,"fat":9},{"name":"cúrcuma / turmeric","quantity":5,"unit":"g","calories":16,"protein":0,"carbs":3,"fat":0},{"name":"jengibre / ginger","quantity":10,"unit":"g","calories":8,"protein":0,"carbs":2,"fat":0},{"name":"espinaca baby / baby spinach","quantity":50,"unit":"g","calories":12,"protein":2,"carbs":2,"fat":0},{"name":"limón / lemon","quantity":1,"unit":"unidad","calories":20,"protein":0,"carbs":7,"fat":0}]',
 '1. Cocinar arroz con cúrcuma y jengibre. 2. Asar salmón 12-15 min. 3. Preparar bowl con arroz base y espinaca. 4. Agregar salmón y aguacate en láminas. 5. Exprimir limón y sazonar.',
 624, 57, 41, 27, 7, 280,
 '["recovery","anti-inflammatory","omega3","high-protein","post_race"]', '["runners","cyclists","triathletes","swimmers"]',
 'https://images.pexels.com/photos/2664216/pexels-photo-2664216.jpeg', true),

(NULL, 'Leche dorada de recuperación / Golden Recovery Milk', 'Leche dorada de recuperación', 'Golden Recovery Milk', 'indian',
 'Leche caliente con cúrcuma, canela, jengibre y pimienta negra, antiinflamatoria | Hot milk with turmeric, cinnamon, ginger and black pepper, anti-inflammatory',
 'snack', 5, 5, 1,
 '[{"name":"leche / milk","quantity":300,"unit":"ml","calories":183,"protein":9,"carbs":14,"fat":8},{"name":"cúrcuma / turmeric","quantity":5,"unit":"g","calories":16,"protein":0,"carbs":3,"fat":0},{"name":"canela / cinnamon","quantity":2,"unit":"g","calories":5,"protein":0,"carbs":2,"fat":0},{"name":"jengibre en polvo / ground ginger","quantity":2,"unit":"g","calories":7,"protein":0,"carbs":1,"fat":0},{"name":"pimienta negra / black pepper","quantity":1,"unit":"g","calories":3,"protein":0,"carbs":1,"fat":0},{"name":"miel / honey","quantity":10,"unit":"ml","calories":30,"protein":0,"carbs":8,"fat":0}]',
 '1. Calentar leche sin hervir. 2. Agregar cúrcuma, canela, jengibre y pimienta. 3. Revolver bien. 4. Añadir miel. 5. Servir caliente antes de dormir.',
 244, 29, 9, 8, 1, 120,
 '["snack","anti-inflammatory","recovery","sleep","ayurveda"]', '["runners","cyclists","triathletes","swimmers"]',
 'https://images.pexels.com/photos/3026804/pexels-photo-3026804.jpeg', true),

(NULL, 'Cena de carga Ironman / Ironman Carb Load Dinner', 'Cena de carga de carbohidratos Ironman', 'Ironman Carbohydrate Loading Dinner', 'global',
 'Cena de carga máxima de carbohidratos para la noche antes de un Ironman | Maximum carbohydrate loading dinner for the night before an Ironman',
 'pre_race', 15, 25, 1,
 '[{"name":"pasta blanca / white pasta","quantity":180,"unit":"g","calories":648,"protein":22,"carbs":130,"fat":2},{"name":"pechuga de pollo / chicken breast","quantity":120,"unit":"g","calories":198,"protein":37,"carbs":0,"fat":4},{"name":"tomate en salsa / tomato sauce","quantity":100,"unit":"g","calories":33,"protein":2,"carbs":7,"fat":0},{"name":"pan blanco / white bread","quantity":60,"unit":"g","calories":160,"protein":5,"carbs":32,"fat":1},{"name":"arroz con leche / rice pudding","quantity":100,"unit":"g","calories":150,"protein":4,"carbs":30,"fat":3},{"name":"jugo de naranja / orange juice","quantity":250,"unit":"ml","calories":108,"protein":2,"carbs":25,"fat":0}]',
 '1. Cocer pasta al dente con salsa ligera. 2. Añadir pollo hervido desmenuzado. 3. Acompañar con pan blanco. 4. De postre, arroz con leche. 5. Beber jugo de naranja. 6. Comer 3-4h antes de dormir.',
 1297, 224, 72, 10, 4, 480,
 '["pre_race","carb-loading","ironman","triathlon","max-carbs"]', '["triathletes","swimmers","cyclists","runners"]',
 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg', true),

(NULL, 'Batido post-Ironman / Post-Ironman Recovery Shake', 'Batido de recuperación post-Ironman', 'Post-Ironman Recovery Shake', 'global',
 'Batido de recuperación intensiva tras un Ironman, 4:1 carbohidrato:proteína | Intensive recovery shake after an Ironman, 4:1 carbohydrate to protein ratio',
 'post_race', 5, 0, 1,
 '[{"name":"proteína de suero / whey protein","quantity":40,"unit":"g","calories":160,"protein":32,"carbs":4,"fat":2},{"name":"leche / milk","quantity":300,"unit":"ml","calories":183,"protein":9,"carbs":14,"fat":8},{"name":"plátano / banana","quantity":2,"unit":"mediano","calories":178,"protein":2,"carbs":46,"fat":1},{"name":"mantequilla de maní / peanut butter","quantity":15,"unit":"g","calories":90,"protein":4,"carbs":3,"fat":8},{"name":"miel / honey","quantity":20,"unit":"ml","calories":60,"protein":0,"carbs":16,"fat":0}]',
 '1. Licuar todos los ingredientes. 2. Consumir inmediatamente post-llegada. 3. Seguir con alimentación sólida dentro de 2h.',
 671, 83, 47, 19, 2, 220,
 '["post_race","recovery","ironman","triathlon","high-protein","4-1-ratio"]', '["triathletes","swimmers","cyclists","runners"]',
 'https://images.pexels.com/photos/1633578/pexels-photo-1633578.jpeg', true),

(NULL, 'Caldo de altura para atletas / Altitude Training Broth', 'Caldo de pollo para entrenamiento en altura', 'Altitude Training Chicken Broth', 'global',
 'Caldo reconfortante con hierro y electrolitos para atletas que entrenan en altura | Comforting broth with iron and electrolytes for athletes training at altitude',
 'recovery', 10, 45, 2,
 '[{"name":"pollo / chicken","quantity":300,"unit":"g","calories":495,"protein":92,"carbs":0,"fat":11},{"name":"espinaca / spinach","quantity":100,"unit":"g","calories":23,"protein":3,"carbs":4,"fat":0},{"name":"lentejas / lentils","quantity":80,"unit":"g","calories":93,"protein":7,"carbs":16,"fat":0},{"name":"cebolla / onion","quantity":80,"unit":"g","calories":32,"protein":1,"carbs":7,"fat":0},{"name":"sal marina / sea salt","quantity":5,"unit":"g","calories":0,"protein":0,"carbs":0,"fat":0},{"name":"limón / lemon","quantity":1,"unit":"unidad","calories":20,"protein":0,"carbs":7,"fat":0}]',
 '1. Hervir pollo con cebolla y sal 30 min. 2. Agregar lentejas y cocinar 15 min. 3. Incorporar espinaca últimos 5 min. 4. Exprimir limón al servir. 5. Beber como caldo o comer con pan.',
 663, 34, 103, 12, 8, 820,
 '["recovery","altitude","iron-rich","electrolytes","high-protein"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/3297948/pexels-photo-3297948.jpeg', true),

(NULL, 'Requesón nocturno de recuperación / Night Recovery Cottage Cheese', 'Requesón nocturno de recuperación', 'Night Recovery Cottage Cheese', 'global',
 'Bowl nocturno de requesón con frutas y semillas para recuperación muscular durante el sueño | Night bowl of cottage cheese with fruits and seeds for muscle recovery during sleep',
 'recovery', 5, 0, 1,
 '[{"name":"requesón / cottage cheese","quantity":200,"unit":"g","calories":180,"protein":28,"carbs":6,"fat":5},{"name":"arándanos / blueberries","quantity":60,"unit":"g","calories":34,"protein":0,"carbs":9,"fat":0},{"name":"semillas de calabaza / pumpkin seeds","quantity":15,"unit":"g","calories":83,"protein":4,"carbs":2,"fat":7},{"name":"miel / honey","quantity":10,"unit":"ml","calories":30,"protein":0,"carbs":8,"fat":0},{"name":"almendras / almonds","quantity":15,"unit":"g","calories":87,"protein":3,"carbs":3,"fat":8}]',
 '1. Colocar requesón en bowl. 2. Cubrir con arándanos frescos. 3. Agregar semillas de calabaza y almendras. 4. Rociar con miel. 5. Consumir 30 min antes de dormir.',
 414, 28, 35, 20, 3, 480,
 '["recovery","night","casein","muscle-growth","sleep"]', '["runners","cyclists","triathletes","swimmers"]',
 'https://images.pexels.com/photos/1640771/pexels-photo-1640771.jpeg', true),

(NULL, 'Bebida deportiva casera / Homemade Sports Drink', 'Bebida deportiva casera con sal y limón', 'Homemade Lemon Salt Sports Drink', 'global',
 'Bebida isotónica casera con limón, sal y azúcar para reponer electrolitos | Homemade isotonic drink with lemon, salt and sugar to replenish electrolytes',
 'during_race', 5, 0, 2,
 '[{"name":"agua / water","quantity":500,"unit":"ml","calories":0,"protein":0,"carbs":0,"fat":0},{"name":"jugo de limón / lemon juice","quantity":60,"unit":"ml","calories":16,"protein":0,"carbs":5,"fat":0},{"name":"azúcar / sugar","quantity":30,"unit":"g","calories":116,"protein":0,"carbs":30,"fat":0},{"name":"sal marina / sea salt","quantity":2,"unit":"g","calories":0,"protein":0,"carbs":0,"fat":0},{"name":"bicarbonato / baking soda","quantity":1,"unit":"g","calories":0,"protein":0,"carbs":0,"fat":0}]',
 '1. Disolver azúcar y sal en 100ml de agua caliente. 2. Agregar el agua fría restante. 3. Añadir limón y bicarbonato. 4. Revolver bien. 5. Llevar en botella para carrera.',
 132, 35, 0, 0, 0, 520,
 '["during_race","hydration","electrolytes","homemade","isotonic","vegan"]', '["runners","cyclists","triathletes","swimmers"]',
 'https://images.pexels.com/photos/3026804/pexels-photo-3026804.jpeg', true),

(NULL, 'Porridge de teff con miel y nueces / Teff Porridge', 'Porridge de teff con miel y nueces', 'Teff Porridge with Honey and Nuts', 'ethiopian',
 'Gachas espesas de teff etíope con nueces y miel, desayuno de campeones | Thick Ethiopian teff porridge with nuts and honey, champions breakfast',
 'breakfast', 5, 15, 1,
 '[{"name":"harina de teff / teff flour","quantity":80,"unit":"g","calories":288,"protein":10,"carbs":59,"fat":2},{"name":"leche / milk","quantity":200,"unit":"ml","calories":122,"protein":6,"carbs":9,"fat":6},{"name":"nueces / walnuts","quantity":20,"unit":"g","calories":131,"protein":3,"carbs":3,"fat":13},{"name":"miel / honey","quantity":20,"unit":"ml","calories":60,"protein":0,"carbs":16,"fat":0},{"name":"canela / cinnamon","quantity":2,"unit":"g","calories":5,"protein":0,"carbs":2,"fat":0},{"name":"plátano / banana","quantity":1,"unit":"mediano","calories":89,"protein":1,"carbs":23,"fat":0}]',
 '1. Mezclar teff con leche hasta sin grumos. 2. Cocinar a fuego medio 12-15 min revolviendo. 3. Servir con nueces, miel, canela y plátano.',
 695, 112, 20, 21, 7, 95,
 '["breakfast","pre-race","ethiopian","teff","gluten-free"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/1510701/pexels-photo-1510701.jpeg', true),

(NULL, 'Tibs etíope de cordero / Ethiopian Lamb Tibs', 'Tibs etíope de cordero', 'Ethiopian Lamb Tibs', 'ethiopian',
 'Cordero salteado etíope con berbere y verduras, plato post-entrenamiento | Ethiopian sautéed lamb with berbere and vegetables, post-training dish',
 'dinner', 15, 20, 2,
 '[{"name":"cordero / lamb","quantity":250,"unit":"g","calories":368,"protein":38,"carbs":0,"fat":24},{"name":"pimiento / bell pepper","quantity":80,"unit":"g","calories":25,"protein":1,"carbs":5,"fat":0},{"name":"cebolla / onion","quantity":80,"unit":"g","calories":32,"protein":1,"carbs":7,"fat":0},{"name":"berbere","quantity":15,"unit":"g","calories":45,"protein":2,"carbs":8,"fat":2},{"name":"mantequilla niter kibbeh","quantity":20,"unit":"g","calories":172,"protein":0,"carbs":0,"fat":19},{"name":"injera / injera bread","quantity":100,"unit":"g","calories":160,"protein":5,"carbs":30,"fat":3}]',
 '1. Cortar cordero en cubos. 2. Derretir niter kibbeh en sartén caliente. 3. Sellar cordero. 4. Agregar cebolla, pimiento y berbere. 5. Saltear 10 min a fuego alto. 6. Servir sobre injera.',
 802, 50, 47, 45, 5, 680,
 '["dinner","high-protein","ethiopian","berbere","traditional"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/2233729/pexels-photo-2233729.jpeg', true),

(NULL, 'Nyama choma keniano / Kenyan Nyama Choma', 'Nyama choma keniano con ugali', 'Kenyan Nyama Choma', 'kenyan',
 'Carne asada keniana con ugali y kachumbari, plato de celebración | Kenyan roasted meat with ugali and kachumbari, celebration dish',
 'dinner', 20, 45, 2,
 '[{"name":"costillas de cabra / goat ribs","quantity":300,"unit":"g","calories":540,"protein":48,"carbs":0,"fat":38},{"name":"harina de maíz ugali / corn flour","quantity":150,"unit":"g","calories":543,"protein":12,"carbs":115,"fat":3},{"name":"tomate / tomato","quantity":100,"unit":"g","calories":18,"protein":1,"carbs":4,"fat":0},{"name":"cebolla / onion","quantity":60,"unit":"g","calories":24,"protein":1,"carbs":6,"fat":0},{"name":"cilantro / cilantro","quantity":10,"unit":"g","calories":2,"protein":0,"carbs":0,"fat":0},{"name":"lima / lime","quantity":1,"unit":"unidad","calories":20,"protein":0,"carbs":7,"fat":0}]',
 '1. Sazonar carne con sal y ajo. 2. Asar en parrilla o horno 40 min dando vuelta. 3. Hacer ugali: hervir agua, agregar harina revolviendo hasta firme. 4. Kachumbari: tomate, cebolla, cilantro y lima. 5. Servir carne con ugali y kachumbari.',
 1147, 132, 61, 41, 8, 680,
 '["dinner","high-protein","kenyan","celebration","traditional"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/1640776/pexels-photo-1640776.jpeg', true),

(NULL, 'Smoothie bowl proteína verde / Green Protein Smoothie Bowl', 'Smoothie bowl de proteína verde', 'Green Protein Smoothie Bowl', 'global',
 'Bowl espeso de espinaca, plátano y proteína verde, rico en hierro | Thick bowl of spinach, banana and protein, rich in iron',
 'breakfast', 10, 0, 1,
 '[{"name":"espinaca / spinach","quantity":60,"unit":"g","calories":14,"protein":2,"carbs":2,"fat":0},{"name":"plátano congelado / frozen banana","quantity":2,"unit":"mediano","calories":178,"protein":2,"carbs":46,"fat":1},{"name":"proteína de vainilla / vanilla protein","quantity":25,"unit":"g","calories":100,"protein":20,"carbs":2,"fat":2},{"name":"leche de almendras / almond milk","quantity":100,"unit":"ml","calories":39,"protein":1,"carbs":2,"fat":3},{"name":"granola / granola","quantity":40,"unit":"g","calories":180,"protein":5,"carbs":30,"fat":6},{"name":"kiwi / kiwi","quantity":1,"unit":"unidad","calories":42,"protein":1,"carbs":10,"fat":0}]',
 '1. Licuar espinaca con plátano, proteína y leche hasta muy espeso. 2. Verter en bowl. 3. Cubrir con granola, kiwi cortado y semillas. 4. Consumir inmediatamente.',
 553, 92, 31, 12, 7, 120,
 '["breakfast","iron-rich","pre-race","green","vegan-option"]', '["runners","cyclists","triathletes","swimmers"]',
 'https://images.pexels.com/photos/1633578/pexels-photo-1633578.jpeg', true),

(NULL, 'Wrap de pollo y hummus mediterráneo / Mediterranean Chicken Hummus Wrap', 'Wrap de pollo y hummus mediterráneo', 'Mediterranean Chicken Hummus Wrap', 'mediterranean',
 'Wrap de tortilla integral con pollo, hummus, verduras asadas y feta | Whole wheat tortilla wrap with chicken, hummus, roasted vegetables and feta',
 'lunch', 15, 20, 1,
 '[{"name":"tortilla integral / whole wheat tortilla","quantity":60,"unit":"g","calories":197,"protein":6,"carbs":36,"fat":4},{"name":"pechuga de pollo / chicken breast","quantity":120,"unit":"g","calories":198,"protein":37,"carbs":0,"fat":4},{"name":"hummus","quantity":40,"unit":"g","calories":94,"protein":4,"carbs":10,"fat":5},{"name":"pimiento rojo asado / roasted red pepper","quantity":60,"unit":"g","calories":30,"protein":1,"carbs":6,"fat":0},{"name":"rúcula / arugula","quantity":20,"unit":"g","calories":5,"protein":0,"carbs":1,"fat":0},{"name":"queso feta / feta cheese","quantity":30,"unit":"g","calories":80,"protein":4,"carbs":1,"fat":6}]',
 '1. Cocinar pollo sazonado a la plancha. 2. Calentar tortilla. 3. Untar hummus. 4. Añadir rúcula, pimiento, pollo y feta. 5. Enrollar firmemente y cortar en diagonal.',
 604, 54, 52, 19, 5, 780,
 '["lunch","portable","high-protein","mediterranean","balanced"]', '["runners","cyclists","triathletes","swimmers"]',
 'https://images.pexels.com/photos/1640773/pexels-photo-1640773.jpeg', true),

(NULL, 'Asado argentino post-entrenamiento / Post-Training Argentine Asado', 'Asado argentino post-entrenamiento', 'Post-Training Argentine Asado', 'latin_american',
 'Cortes magros de asado argentino con chimichurri y vegetales | Lean cuts of Argentine asado with chimichurri and vegetables',
 'dinner', 20, 40, 2,
 '[{"name":"entraña / skirt steak","quantity":200,"unit":"g","calories":376,"protein":36,"carbs":0,"fat":26},{"name":"vacío / flank steak","quantity":150,"unit":"g","calories":249,"protein":30,"carbs":0,"fat":14},{"name":"chorizo criollo / criollo sausage","quantity":80,"unit":"g","calories":264,"protein":12,"carbs":1,"fat":24},{"name":"ajo / garlic","quantity":15,"unit":"g","calories":20,"protein":1,"carbs":5,"fat":0},{"name":"perejil / parsley","quantity":20,"unit":"g","calories":7,"protein":1,"carbs":1,"fat":0},{"name":"vinagre / vinegar","quantity":15,"unit":"ml","calories":4,"protein":0,"carbs":1,"fat":0}]',
 '1. Encender parrilla. 2. Sazonar carnes con sal gruesa. 3. Asar a fuego medio, dar vuelta una vez. 4. Preparar chimichurri con ajo, perejil, aceite y vinagre. 5. Servir con papas a las brasas y ensalada.',
 920, 8, 79, 64, 1, 680,
 '["dinner","high-protein","argentinian","asado","traditional"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/1640776/pexels-photo-1640776.jpeg', true),

(NULL, 'Cocido madrileño de deportista / Athlete Madrid Stew', 'Cocido madrileño de deportista', 'Athlete Madrid Chickpea Stew', 'spanish',
 'Guiso madrileño de garbanzos, pollo y verduras, reconfortante y energético | Madrid stew of chickpeas, chicken and vegetables, comforting and energetic',
 'dinner', 20, 90, 3,
 '[{"name":"garbanzos cocidos / cooked chickpeas","quantity":200,"unit":"g","calories":328,"protein":18,"carbs":55,"fat":5},{"name":"pollo / chicken","quantity":250,"unit":"g","calories":413,"protein":77,"carbs":0,"fat":9},{"name":"papa / potato","quantity":200,"unit":"g","calories":154,"protein":4,"carbs":35,"fat":0},{"name":"zanahoria / carrot","quantity":100,"unit":"g","calories":41,"protein":1,"carbs":10,"fat":0},{"name":"apio / celery","quantity":60,"unit":"g","calories":10,"protein":0,"carbs":2,"fat":0},{"name":"morcilla / blood sausage","quantity":60,"unit":"g","calories":180,"protein":8,"carbs":3,"fat":16},{"name":"caldo / broth","quantity":600,"unit":"ml","calories":24,"protein":2,"carbs":4,"fat":0}]',
 '1. Remojar garbanzos la noche anterior. 2. Hervir pollo y garbanzos 1h. 3. Agregar papa, zanahoria y apio. 4. Cocinar 30 min más. 5. Agregar morcilla últimos 10 min. 6. Servir por separado: sopa, garbanzos y carnes.',
 1150, 109, 110, 30, 16, 820,
 '["dinner","high-protein","carb-loading","spanish","traditional","recovery"]', '["runners","cyclists","triathletes"]',
 'https://images.pexels.com/photos/5409010/pexels-photo-5409010.jpeg', true);
